// Default
export const PROGRESS = 'PROGRESS';
export const INC_PROGRESS = 'INC_PROGRESS';

// Project Detail
export const HUB_PROJECT = 'HUB_PROJECT';
export const HUB_PROJECT_UPDATE = 'HUB_PROJECT_UPDATE';
export const HUB_PROJECT_UPDATE_START = 'HUB_PROJECT_UPDATE_START';
export const HUB_PROJECT_UPDATE_DONE = 'HUB_PROJECT_UPDATE_DONE';
export const HUB_PROJECT_UPDATE_STATUS_DONE = 'HUB_PROJECT_UPDATE_STATUS_DONE';
export const HUB_PROJECT_STATE_RESET = 'HUB_PROJECT_STATE_RESET';
export const HUB_PROJECT_NOT_FOUND = 'HUB_PROJECT_NOT_FOUND';

// Control Panel
export const PANEL_SET_DATA = 'PANEL_SET_DATA';
export const PANEL_LOADING_STATUS = 'PANEL_LOADING_STATUS';
