export const MonacoConfig: any = {
  height: '21px',
  options: {
    lineNumbers: 'off',
    minimap: { enabled: false },
    fontFamily: 'Iosevka',
    wordWrap: 'off',
    fontSize: 14,
    lineNumbersMinChars: 0,
    overviewRulerLanes: 0,
    overviewRulerBorder: false,
    lineDecorationsWidth: 0,
    hideCursorInOverviewRuler: true,
    contextmenu: false,
    glyphMargin: false,
    folding: false,
    scrollBeyondLastColumn: 0,
    renderLineHighlight: 'none',
    scrollbar: { horizontal: 'hidden', vertical: 'hidden' },
    find: {
      addExtraSpaceOnTop: false,
      autoFindInSelection: 'never',
      seedSearchStringFromSelection: 'never',
    },
  },
  theme: {
    base: 'vs',
    inherit: true,
    rules: [{ background: 'ffffff' }],
    colors: {
      'editor.foreground': '#000000',
      'editor.background': '#ffffff',
      'editorCursor.foreground': '#83899e',
      'dropdown.background': '#fff',
      'editorSuggestWidget.background': '#fff',
      'editorSuggestWidget.border': '#dceafb',
      'editorSuggestWidget.selectedBackground': '#dceafb',
      // findMatchHighlightBackground: '#fff',
      'editorSuggestWidget.foreground': '#414b6d',
      'editorSuggestWidget.highlightForeground': '#414b6d',
    },
  },
};
