export const colorOptions = [
  { name: 'bleu', group: 'metric' },
  { name: 'best_loss', group: 'metric' },
  { name: 'bsz', group: 'metric' },
  { name: 'gnorm', group: 'metric' },
  { name: 'label_smoothing', group: 'hparams' },
  { name: 'learning_rate', group: 'hparams' },
  { name: 'max_k', group: 'hparams' },
  { name: 'max_tokens', group: 'hparams' },
  { name: 'method', group: 'hparams' },
  { name: 'normalize', group: 'hparams' },
];

export const metricOptions = [
  { name: 'bleu', group: 'metric' },
  { name: 'best_loss', group: 'metric' },
  { name: 'bsz', group: 'metric' },
  { name: 'gnorm', group: 'metric' },
  { name: 'loss', group: 'metric' },
  { name: 'loss_scale', group: 'metric' },
  { name: 'lr', group: 'metric' },
  { name: 'nll_loss', group: 'metric' },
  { name: 'ppl', group: 'metric' },
  { name: 'train_wall', group: 'metric' },
  { name: 'ups', group: 'metric' },
  { name: 'wall', group: 'metric' },
  { name: 'wpb', group: 'metric' },
  { name: 'wps', group: 'metric' },
  { name: 'label_smoothing', group: 'hparams' },
  { name: 'learning_rate', group: 'hparams' },
  { name: 'max_k', group: 'hparams' },
  { name: 'max_tokens', group: 'hparams' },
  { name: 'method', group: 'hparams' },
  { name: 'normalize', group: 'hparams' },
  { name: 'pooling', group: 'hparams' },
  { name: 'seed', group: 'hparams' },
  { name: 'seg', group: 'hparams' },
  { name: 'upscale_primary', group: 'hparams' },
  { name: 'warmup_steps', group: 'hparams' },
];

export const COLORS = [
  [
    '#16A085',
    '#B33771',
    '#2980B9',
    '#e74c3c',
    '#8E44AD',
    '#34495E',
    '#e5bc22',
    '#888888',
  ],
  [
    '#336699',
    '#339966',
    '#993399',
    '#999966',
    '#669966',
    '#663333',
    '#669999',
    '#663366',
    '#666633',
    '#996666',
    '#999933',
    '#669933',
    '#663399',
    '#666699',
    '#993366',
    '#996633',
    '#996699',
    '#339999',
    '#333366',
    '#336633',
    '#333399',
    '#339933',
    '#336666',
    '#FD7272',
  ],
];
