export const colorOptions = [
  { name: 'bleu', group: 'metric' },
  { name: 'best_loss', group: 'metric' },
  { name: 'bsz', group: 'metric' },
  { name: 'gnorm', group: 'metric' },
  { name: 'label_smoothing', group: 'hparams' },
  { name: 'learning_rate', group: 'hparams' },
  { name: 'max_k', group: 'hparams' },
  { name: 'max_tokens', group: 'hparams' },
  { name: 'method', group: 'hparams' },
  { name: 'normalize', group: 'hparams' },
];

export const metricOptions = [
  { name: 'bleu', group: 'metric' },
  { name: 'best_loss', group: 'metric' },
  { name: 'bsz', group: 'metric' },
  { name: 'gnorm', group: 'metric' },
  { name: 'loss', group: 'metric' },
  { name: 'loss_scale', group: 'metric' },
  { name: 'lr', group: 'metric' },
  { name: 'nll_loss', group: 'metric' },
  { name: 'ppl', group: 'metric' },
  { name: 'train_wall', group: 'metric' },
  { name: 'ups', group: 'metric' },
  { name: 'wall', group: 'metric' },
  { name: 'wpb', group: 'metric' },
  { name: 'wps', group: 'metric' },
  { name: 'label_smoothing', group: 'hparams' },
  { name: 'learning_rate', group: 'hparams' },
  { name: 'max_k', group: 'hparams' },
  { name: 'max_tokens', group: 'hparams' },
  { name: 'method', group: 'hparams' },
  { name: 'normalize', group: 'hparams' },
  { name: 'pooling', group: 'hparams' },
  { name: 'seed', group: 'hparams' },
  { name: 'seg', group: 'hparams' },
  { name: 'upscale_primary', group: 'hparams' },
  { name: 'warmup_steps', group: 'hparams' },
];
