AIM_REPO_NAME = '.aim'
AIM_OBJECTS_DIR_NAME = 'objects'
AIM_METRICS_DIR_NAME = 'metrics'
AIM_ANNOT_DIR_NAME = 'annotations'
AIM_MEDIA_DIR_NAME = 'media'
AIM_IMAGES_DIR_NAME = 'images'
AIM_MODELS_DIR_NAME = 'models'
AIM_CONFIG_FILE_NAME = 'config.json'
AIM_DEFAULT_BRANCH_NAME = 'default'

AIM_LOGGING_DIR_NAME = 'logs'
AIM_CLI_ACTIVITIED_LOG = 'activities.log'
AIM_SDK_ERROR_LOG = 'errors.log'

AIM_PROFILE_NAME = '.aim_profile'
AIM_PROFILE_CONFIG_FILE_NAME = 'config.json'
AIM_PROFILE_SSH_DIR_NAME = '.ssh'
