const pageTitles = {
  DASHBOARD: '',
  EXPLORERS: 'Explorers',
  RUNS_EXPLORER: 'Runs Explorer',
  METRICS_EXPLORER: 'Metrics Explorer',
  PARAMS_EXPLORER: 'Params Explorer',
  IMAGES_EXPLORER: 'Images Explorer',
  SCATTERS_EXPLORER: 'Scatters Explorer',
  FIGURES_EXPLORER: 'Figures Explorer',
  AUDIOS_EXPLORER: 'Audios Explorer',
  TEXT_EXPLORER: 'Text Explorer',
  PROMPTS_EXPLORER: 'Prompts Explorer',
  BOOKMARKS: 'Bookmarks',
  TAGS: 'Tags',
  RUN_DETAIL: 'Run',
  EXPERIMENT: 'Experiment',
  FIGURES_EXPLORER_NEW: 'New Figures',
  BOARDS: 'Boards',
  BOARD: 'Board',
  REPORTS: 'Reports',
  REPORT: 'Report',
  APP: 'App',
};

export default pageTitles;
