import React from 'react';
import Editor from 'rich-markdown-editor';

import { Text } from 'components/kit';

import { AIM_VERSION } from 'config/config';

import useReleaseNotes from './useReleaseNotes';

const mock = [
  {
    url: 'https://api.github.com/repos/aimhubio/aim/releases/77420093',
    assets_url:
      'https://api.github.com/repos/aimhubio/aim/releases/77420093/assets',
    upload_url:
      'https://uploads.github.com/repos/aimhubio/aim/releases/77420093/assets{?name,label}',
    html_url: 'https://github.com/aimhubio/aim/releases/tag/v3.13.3',
    id: 77420093,
    author: {
      login: 'gorarakelyan',
      id: 13848158,
      node_id: 'MDQ6VXNlcjEzODQ4MTU4',
      avatar_url: 'https://avatars.githubusercontent.com/u/13848158?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/gorarakelyan',
      html_url: 'https://github.com/gorarakelyan',
      followers_url: 'https://api.github.com/users/gorarakelyan/followers',
      following_url:
        'https://api.github.com/users/gorarakelyan/following{/other_user}',
      gists_url: 'https://api.github.com/users/gorarakelyan/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/gorarakelyan/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/gorarakelyan/subscriptions',
      organizations_url: 'https://api.github.com/users/gorarakelyan/orgs',
      repos_url: 'https://api.github.com/users/gorarakelyan/repos',
      events_url: 'https://api.github.com/users/gorarakelyan/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/gorarakelyan/received_events',
      type: 'User',
      site_admin: false,
    },
    node_id: 'RE_kwDOC02th84EnVY9',
    tag_name: 'v3.13.3',
    target_commitish: 'main',
    name: 'v3.13.3 🚀',
    draft: false,
    prerelease: false,
    created_at: '2022-09-16T17:35:26Z',
    published_at: '2022-09-16T18:02:28Z',
    assets: [],
    tarball_url: 'https://api.github.com/repos/aimhubio/aim/tarball/v3.13.3',
    zipball_url: 'https://api.github.com/repos/aimhubio/aim/zipball/v3.13.3',
    body: "## What's Changed\r\n* [fix] Resolve request cancellation issues on `Logs` tab by @mihran113 in https://github.com/aimhubio/aim/pull/2163\r\n* [fix] Fix the data live update handling in the Logs tab by @VkoHov in https://github.com/aimhubio/aim/pull/2167\r\n\r\n\r\n**Full Changelog**: https://github.com/aimhubio/aim/compare/v3.13.2...v3.13.3",
    mentions_count: 2,
  },
  {
    url: 'https://api.github.com/repos/aimhubio/aim/releases/76800801',
    assets_url:
      'https://api.github.com/repos/aimhubio/aim/releases/76800801/assets',
    upload_url:
      'https://uploads.github.com/repos/aimhubio/aim/releases/76800801/assets{?name,label}',
    html_url: 'https://github.com/aimhubio/aim/releases/tag/v3.13.2',
    id: 76800801,
    author: {
      login: 'gorarakelyan',
      id: 13848158,
      node_id: 'MDQ6VXNlcjEzODQ4MTU4',
      avatar_url: 'https://avatars.githubusercontent.com/u/13848158?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/gorarakelyan',
      html_url: 'https://github.com/gorarakelyan',
      followers_url: 'https://api.github.com/users/gorarakelyan/followers',
      following_url:
        'https://api.github.com/users/gorarakelyan/following{/other_user}',
      gists_url: 'https://api.github.com/users/gorarakelyan/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/gorarakelyan/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/gorarakelyan/subscriptions',
      organizations_url: 'https://api.github.com/users/gorarakelyan/orgs',
      repos_url: 'https://api.github.com/users/gorarakelyan/repos',
      events_url: 'https://api.github.com/users/gorarakelyan/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/gorarakelyan/received_events',
      type: 'User',
      site_admin: false,
    },
    node_id: 'RE_kwDOC02th84Ek-Mh',
    tag_name: 'v3.13.2',
    target_commitish: 'main',
    name: 'v3.13.2 🚀',
    draft: false,
    prerelease: false,
    created_at: '2022-09-10T15:25:48Z',
    published_at: '2022-09-10T15:57:10Z',
    assets: [],
    tarball_url: 'https://api.github.com/repos/aimhubio/aim/tarball/v3.13.2',
    zipball_url: 'https://api.github.com/repos/aimhubio/aim/zipball/v3.13.2',
    body: "## What's Changed\r\n\r\n* [fix] Fix content overlapping issue of x-axis alignment dropdown by @KaroMourad in https://github.com/aimhubio/aim/pull/2157\r\n* [fix] Fix regression line rendering issue on scatterplot exported image by @KaroMourad in https://github.com/aimhubio/aim/pull/2157\r\n\r\n\r\n**Full Changelog**: https://github.com/aimhubio/aim/compare/v3.13.1...v3.13.2",
    mentions_count: 1,
  },
  {
    url: 'https://api.github.com/repos/aimhubio/aim/releases/76086464',
    assets_url:
      'https://api.github.com/repos/aimhubio/aim/releases/76086464/assets',
    upload_url:
      'https://uploads.github.com/repos/aimhubio/aim/releases/76086464/assets{?name,label}',
    html_url: 'https://github.com/aimhubio/aim/releases/tag/v3.13.1',
    id: 76086464,
    author: {
      login: 'gorarakelyan',
      id: 13848158,
      node_id: 'MDQ6VXNlcjEzODQ4MTU4',
      avatar_url: 'https://avatars.githubusercontent.com/u/13848158?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/gorarakelyan',
      html_url: 'https://github.com/gorarakelyan',
      followers_url: 'https://api.github.com/users/gorarakelyan/followers',
      following_url:
        'https://api.github.com/users/gorarakelyan/following{/other_user}',
      gists_url: 'https://api.github.com/users/gorarakelyan/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/gorarakelyan/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/gorarakelyan/subscriptions',
      organizations_url: 'https://api.github.com/users/gorarakelyan/orgs',
      repos_url: 'https://api.github.com/users/gorarakelyan/repos',
      events_url: 'https://api.github.com/users/gorarakelyan/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/gorarakelyan/received_events',
      type: 'User',
      site_admin: false,
    },
    node_id: 'RE_kwDOC02th84EiPzA',
    tag_name: 'v3.13.1',
    target_commitish: 'main',
    name: 'v3.13.1 🚀',
    draft: false,
    prerelease: false,
    created_at: '2022-09-01T19:15:54Z',
    published_at: '2022-09-01T20:08:48Z',
    assets: [],
    tarball_url: 'https://api.github.com/repos/aimhubio/aim/tarball/v3.13.1',
    zipball_url: 'https://api.github.com/repos/aimhubio/aim/zipball/v3.13.1',
    body: "## What's Changed\r\n* [fix] Add wandb section link on converters page by @tmynn in https://github.com/aimhubio/aim/pull/2113\r\n* [fix] Tune error message when KerasTuner is not installed by @tmynn in https://github.com/aimhubio/aim/pull/2114\r\n* [fix] Change method used for setting Run finalization time by @alberttorosyan in https://github.com/aimhubio/aim/pull/2119\r\n* [fix] Resolve issue with remote runs re-open by @mihran113 in https://github.com/aimhubio/aim/pull/2128\r\n* [deprecation] Warn about deprecation when custom Run.hash is set by @alberttorosyan in https://github.com/aimhubio/aim/pull/2118\r\n* [feat] Add support for metrics query with last value by @mihran113 in https://github.com/aimhubio/aim/pull/2096\r\n* [feat] Tune mlflow converter run properties by @tmynn in https://github.com/aimhubio/aim/pull/2134\r\n* [fix] Deprecation issues with PL v1.7 by @djwessel in https://github.com/aimhubio/aim/pull/2138\r\n\r\n\r\n**Full Changelog**: https://github.com/aimhubio/aim/compare/v3.13.0...v3.13.1",
    mentions_count: 4,
  },
  {
    url: 'https://api.github.com/repos/aimhubio/aim/releases/74926879',
    assets_url:
      'https://api.github.com/repos/aimhubio/aim/releases/74926879/assets',
    upload_url:
      'https://uploads.github.com/repos/aimhubio/aim/releases/74926879/assets{?name,label}',
    html_url: 'https://github.com/aimhubio/aim/releases/tag/v3.13.0',
    id: 74926879,
    author: {
      login: 'gorarakelyan',
      id: 13848158,
      node_id: 'MDQ6VXNlcjEzODQ4MTU4',
      avatar_url: 'https://avatars.githubusercontent.com/u/13848158?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/gorarakelyan',
      html_url: 'https://github.com/gorarakelyan',
      followers_url: 'https://api.github.com/users/gorarakelyan/followers',
      following_url:
        'https://api.github.com/users/gorarakelyan/following{/other_user}',
      gists_url: 'https://api.github.com/users/gorarakelyan/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/gorarakelyan/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/gorarakelyan/subscriptions',
      organizations_url: 'https://api.github.com/users/gorarakelyan/orgs',
      repos_url: 'https://api.github.com/users/gorarakelyan/repos',
      events_url: 'https://api.github.com/users/gorarakelyan/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/gorarakelyan/received_events',
      type: 'User',
      site_admin: false,
    },
    node_id: 'RE_kwDOC02th84Ed0sf',
    tag_name: 'v3.13.0',
    target_commitish: 'main',
    name: 'v3.13.0 🚀',
    draft: false,
    prerelease: false,
    created_at: '2022-08-21T08:09:25Z',
    published_at: '2022-08-21T08:49:28Z',
    assets: [],
    tarball_url: 'https://api.github.com/repos/aimhubio/aim/tarball/v3.13.0',
    zipball_url: 'https://api.github.com/repos/aimhubio/aim/zipball/v3.13.0',
    body: "## What's Changed\r\n\r\n### Enhancements:\r\n\r\n- Add Figures Explorer to visualize and compare plotly figures (@rubenaprikyan, @KaroMourad, @arsengit, @VkoHov, @roubkar)\r\n- Add Base Explorer as core of all explorers (@rubenaprikyan, @KaroMourad, @arsengit, @VkoHov, @roubkar)\r\n- Add logging for remote resource cleanup and network stability (@mihran113)\r\n- Restrict Run.hash to auto-generated values only (@alberttorosyan)\r\n- Add ability to compare selected runs from the table (@arsengit)\r\n- Notify users about failed/stalled runs (@mahnerak, @alberttorosyan)\r\n- Add ability to pin metrics in Run Page (@mihran113, @roubkar)\r\n- Add step for unit tests for nightly releases workflow (@mihran113)\r\n- Add Keras-Tuner integration (@tmynn)\r\n- Add Weights & Biases to Aim log converter (@tmynn)\r\n\r\n### Fixes:\r\n\r\n- Fix chart exporting issue (@KaroMourad)\r\n- Fix aim ui rendering issue on notebooks (@rubenaprikyan)\r\n- Fix live update retry to show live data after solving connection problems with the server (@rubenaprikyan)\r\n- Fix tensorboard convert while converting tensor (@sharathmk99)\r\n- Fix git info collection (@mihran113)\r\n- Fix code block content and query copying functionality (@arsengit)\r\n- Provide compatibility between plotly and matplotlib (@tmynn)\r\n- Warn to use aim.Image if aim.Figure fails (@tmynn)\r\n\r\n## New Contributors\r\n* @Sharathmk99 made their first contribution in https://github.com/aimhubio/aim/pull/2000\r\n* @tmynn made their first contribution in https://github.com/aimhubio/aim/pull/2032\r\n\r\n**Full Changelog**: https://github.com/aimhubio/aim/compare/v3.12.2...v3.13.0",
    mentions_count: 10,
  },
  {
    url: 'https://api.github.com/repos/aimhubio/aim/releases/73785569',
    assets_url:
      'https://api.github.com/repos/aimhubio/aim/releases/73785569/assets',
    upload_url:
      'https://uploads.github.com/repos/aimhubio/aim/releases/73785569/assets{?name,label}',
    html_url: 'https://github.com/aimhubio/aim/releases/tag/v3.12.2',
    id: 73785569,
    author: {
      login: 'gorarakelyan',
      id: 13848158,
      node_id: 'MDQ6VXNlcjEzODQ4MTU4',
      avatar_url: 'https://avatars.githubusercontent.com/u/13848158?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/gorarakelyan',
      html_url: 'https://github.com/gorarakelyan',
      followers_url: 'https://api.github.com/users/gorarakelyan/followers',
      following_url:
        'https://api.github.com/users/gorarakelyan/following{/other_user}',
      gists_url: 'https://api.github.com/users/gorarakelyan/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/gorarakelyan/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/gorarakelyan/subscriptions',
      organizations_url: 'https://api.github.com/users/gorarakelyan/orgs',
      repos_url: 'https://api.github.com/users/gorarakelyan/repos',
      events_url: 'https://api.github.com/users/gorarakelyan/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/gorarakelyan/received_events',
      type: 'User',
      site_admin: false,
    },
    node_id: 'RE_kwDOC02th84EZeDh',
    tag_name: 'v3.12.2',
    target_commitish: 'main',
    name: 'v3.12.2 🚀',
    draft: false,
    prerelease: false,
    created_at: '2022-08-05T19:48:57Z',
    published_at: '2022-08-05T20:02:32Z',
    assets: [],
    tarball_url: 'https://api.github.com/repos/aimhubio/aim/tarball/v3.12.2',
    zipball_url: 'https://api.github.com/repos/aimhubio/aim/zipball/v3.12.2',
    body: "## What's Changed\r\n* [feat] Apply lazy loading on metrics in Run Page by @roubkar in https://github.com/aimhubio/aim/pull/2030\r\n* [fix] Correct metric column key in run table grid by @VkoHov in https://github.com/aimhubio/aim/pull/2038\r\n\r\n**Full Changelog**: https://github.com/aimhubio/aim/compare/v3.12.1...v3.12.2",
    mentions_count: 2,
  },
  {
    url: 'https://api.github.com/repos/aimhubio/aim/releases/73423279',
    assets_url:
      'https://api.github.com/repos/aimhubio/aim/releases/73423279/assets',
    upload_url:
      'https://uploads.github.com/repos/aimhubio/aim/releases/73423279/assets{?name,label}',
    html_url: 'https://github.com/aimhubio/aim/releases/tag/v3.12.1',
    id: 73423279,
    author: {
      login: 'gorarakelyan',
      id: 13848158,
      node_id: 'MDQ6VXNlcjEzODQ4MTU4',
      avatar_url: 'https://avatars.githubusercontent.com/u/13848158?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/gorarakelyan',
      html_url: 'https://github.com/gorarakelyan',
      followers_url: 'https://api.github.com/users/gorarakelyan/followers',
      following_url:
        'https://api.github.com/users/gorarakelyan/following{/other_user}',
      gists_url: 'https://api.github.com/users/gorarakelyan/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/gorarakelyan/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/gorarakelyan/subscriptions',
      organizations_url: 'https://api.github.com/users/gorarakelyan/orgs',
      repos_url: 'https://api.github.com/users/gorarakelyan/repos',
      events_url: 'https://api.github.com/users/gorarakelyan/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/gorarakelyan/received_events',
      type: 'User',
      site_admin: false,
    },
    node_id: 'RE_kwDOC02th84EYFmv',
    tag_name: 'v3.12.1',
    target_commitish: 'main',
    name: 'v3.12.1 🚀',
    draft: false,
    prerelease: false,
    created_at: '2022-08-02T09:36:03Z',
    published_at: '2022-08-02T10:39:03Z',
    assets: [],
    tarball_url: 'https://api.github.com/repos/aimhubio/aim/tarball/v3.12.1',
    zipball_url: 'https://api.github.com/repos/aimhubio/aim/zipball/v3.12.1',
    body: "## What's Changed\r\n* [fix] Break long metric names into multiple lines in Run Page by @roubkar in https://github.com/aimhubio/aim/pull/2001\r\n* [fix] Cython version for setup by @mihran113 in https://github.com/aimhubio/aim/pull/2018\r\n* [fix] Resource cleanup for remote heartbeat-watcher by @mihran113 in https://github.com/aimhubio/aim/pull/2020\r\n* [feat] Enable run filtering by metric values by @mihran113 in https://github.com/aimhubio/aim/pull/2009\r\n* [fix] Loosen version requirements for grpcio by @alberttorosyan in https://github.com/aimhubio/aim/pull/2026\r\n\r\n**Full Changelog**: https://github.com/aimhubio/aim/compare/v3.12.0...v3.12.1",
    mentions_count: 3,
  },
  {
    url: 'https://api.github.com/repos/aimhubio/aim/releases/72642800',
    assets_url:
      'https://api.github.com/repos/aimhubio/aim/releases/72642800/assets',
    upload_url:
      'https://uploads.github.com/repos/aimhubio/aim/releases/72642800/assets{?name,label}',
    html_url: 'https://github.com/aimhubio/aim/releases/tag/v3.12.0',
    id: 72642800,
    author: {
      login: 'gorarakelyan',
      id: 13848158,
      node_id: 'MDQ6VXNlcjEzODQ4MTU4',
      avatar_url: 'https://avatars.githubusercontent.com/u/13848158?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/gorarakelyan',
      html_url: 'https://github.com/gorarakelyan',
      followers_url: 'https://api.github.com/users/gorarakelyan/followers',
      following_url:
        'https://api.github.com/users/gorarakelyan/following{/other_user}',
      gists_url: 'https://api.github.com/users/gorarakelyan/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/gorarakelyan/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/gorarakelyan/subscriptions',
      organizations_url: 'https://api.github.com/users/gorarakelyan/orgs',
      repos_url: 'https://api.github.com/users/gorarakelyan/repos',
      events_url: 'https://api.github.com/users/gorarakelyan/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/gorarakelyan/received_events',
      type: 'User',
      site_admin: false,
    },
    node_id: 'RE_kwDOC02th84EVHDw',
    tag_name: 'v3.12.0',
    target_commitish: 'main',
    name: 'v3.12.0 🚀',
    draft: false,
    prerelease: false,
    created_at: '2022-07-22T18:15:34Z',
    published_at: '2022-07-22T19:08:10Z',
    assets: [],
    tarball_url: 'https://api.github.com/repos/aimhubio/aim/tarball/v3.12.0',
    zipball_url: 'https://api.github.com/repos/aimhubio/aim/zipball/v3.12.0',
    body: "## What's Changed\r\n\r\n### Enhancements:\r\n\r\n- Add ability to set axes range manually for line charts on UI (@KaroMourad)\r\n- Add more user-friendly querying for dates (@mihran113, @arsengit)\r\n- Filter redundant tooltip data from URL config state (@KaroMourad)\r\n- Improve rendering performance by enhancing table columns virtualization mechanism (@roubkar)\r\n- Increase visibility and usability of the Show table diff button (@arsengit)\r\n- Add support for tensorboard audios conversion (@mihran113)\r\n- Format params keys/paths properly (@VkoHov)\r\n- Mention explicitly run params everywhere params is mentioned (@VkoHov)\r\n- Add ability to hide a batch of items in explorers (@VkoHov)\r\n- Add ability to sort by the last value of the metric in table (@VkoHov)\r\n- Preserve active line even if it is dropped out of the filtered area (@VkoHov)\r\n- Add run duration property for SDK and queries (@mihran113)\r\n- Add client vs server version check for remote tracking server (@mihran113)\r\n- Add Remote tracking client heartbeat (@mihran113)\r\n\r\n### Fixes:\r\n\r\n- Tune table sorting icon box overlapping with column box in compact mode (@KaroMourad)\r\n- Fix tensorboard log conversion for images (@mihran113)\r\n- Check if gradient is None when tracking gradient distributions (@kage08)\r\n- Fix displaying non-syntax errors across Aim UI (@arsengit) \r\n- Fix queries on remote repos (@mihran113)\r\n- Fix interval progress reports for query apis (@mihran113)\r\n- Fix query request cancellation errors (@mihran113)\r\n- Auto-detect and address inconsistencies in meta and series trees (@mahnerak)\r\n\r\n## New Contributors\r\n* @kage08 made their first contribution in https://github.com/aimhubio/aim/pull/1917\r\n\r\n**Full Changelog**: https://github.com/aimhubio/aim/compare/v3.11.2...v3.12.0",
    reactions: {
      url: 'https://api.github.com/repos/aimhubio/aim/releases/72642800/reactions',
      total_count: 2,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 1,
      confused: 0,
      heart: 0,
      rocket: 1,
      eyes: 0,
    },
    mentions_count: 7,
  },
  {
    url: 'https://api.github.com/repos/aimhubio/aim/releases/71587069',
    assets_url:
      'https://api.github.com/repos/aimhubio/aim/releases/71587069/assets',
    upload_url:
      'https://uploads.github.com/repos/aimhubio/aim/releases/71587069/assets{?name,label}',
    html_url: 'https://github.com/aimhubio/aim/releases/tag/v3.11.2',
    id: 71587069,
    author: {
      login: 'gorarakelyan',
      id: 13848158,
      node_id: 'MDQ6VXNlcjEzODQ4MTU4',
      avatar_url: 'https://avatars.githubusercontent.com/u/13848158?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/gorarakelyan',
      html_url: 'https://github.com/gorarakelyan',
      followers_url: 'https://api.github.com/users/gorarakelyan/followers',
      following_url:
        'https://api.github.com/users/gorarakelyan/following{/other_user}',
      gists_url: 'https://api.github.com/users/gorarakelyan/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/gorarakelyan/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/gorarakelyan/subscriptions',
      organizations_url: 'https://api.github.com/users/gorarakelyan/orgs',
      repos_url: 'https://api.github.com/users/gorarakelyan/repos',
      events_url: 'https://api.github.com/users/gorarakelyan/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/gorarakelyan/received_events',
      type: 'User',
      site_admin: false,
    },
    node_id: 'RE_kwDOC02th84ERFT9',
    tag_name: 'v3.11.2',
    target_commitish: 'main',
    name: 'v3.11.2 🚀',
    draft: false,
    prerelease: false,
    created_at: '2022-07-08T15:55:20Z',
    published_at: '2022-07-08T17:07:57Z',
    assets: [],
    tarball_url: 'https://api.github.com/repos/aimhubio/aim/tarball/v3.11.2',
    zipball_url: 'https://api.github.com/repos/aimhubio/aim/zipball/v3.11.2',
    body: '## What\'s Changed\r\n* [fix] Fix the "matched runs" sentence color style overriding issue in progress bars by @KaroMourad in https://github.com/aimhubio/aim/pull/1931\r\n* [fix] Fix progress bar blinking issue in Runs Explorer by @KaroMourad in https://github.com/aimhubio/aim/pull/1936\r\n* [fix] Change `SyntaxError` handling for python3.10+ by @mihran113 in https://github.com/aimhubio/aim/pull/1942\r\n* [feat] Display error position after getting syntax errors by @arsengit in https://github.com/aimhubio/aim/pull/1945\r\n* [fix] Avoid saving crashed or terminated search requests as the last state on explorers by @arsengit in https://github.com/aimhubio/aim/pull/1950\r\n* [fix] Prevent the active run indicator appearance out of the chart by @VkoHov in https://github.com/aimhubio/aim/pull/1952\r\n* [fix] Remove error message on explorer unmount by @arsengit in https://github.com/aimhubio/aim/pull/1953\r\n* [fix] Handle generic Exceptions and adjust HTTPException handling by @alberttorosyan in https://github.com/aimhubio/aim/pull/1933\r\n* [fix] Fix error message after getting syntax error by @arsengit in https://github.com/aimhubio/aim/pull/1954\r\n\r\n\r\n**Full Changelog**: https://github.com/aimhubio/aim/compare/v3.11.1...v3.11.2',
    mentions_count: 5,
  },
  {
    url: 'https://api.github.com/repos/aimhubio/aim/releases/70677729',
    assets_url:
      'https://api.github.com/repos/aimhubio/aim/releases/70677729/assets',
    upload_url:
      'https://uploads.github.com/repos/aimhubio/aim/releases/70677729/assets{?name,label}',
    html_url: 'https://github.com/aimhubio/aim/releases/tag/v3.11.1',
    id: 70677729,
    author: {
      login: 'gorarakelyan',
      id: 13848158,
      node_id: 'MDQ6VXNlcjEzODQ4MTU4',
      avatar_url: 'https://avatars.githubusercontent.com/u/13848158?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/gorarakelyan',
      html_url: 'https://github.com/gorarakelyan',
      followers_url: 'https://api.github.com/users/gorarakelyan/followers',
      following_url:
        'https://api.github.com/users/gorarakelyan/following{/other_user}',
      gists_url: 'https://api.github.com/users/gorarakelyan/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/gorarakelyan/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/gorarakelyan/subscriptions',
      organizations_url: 'https://api.github.com/users/gorarakelyan/orgs',
      repos_url: 'https://api.github.com/users/gorarakelyan/repos',
      events_url: 'https://api.github.com/users/gorarakelyan/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/gorarakelyan/received_events',
      type: 'User',
      site_admin: false,
    },
    node_id: 'RE_kwDOC02th84ENnTh',
    tag_name: 'v3.11.1',
    target_commitish: 'main',
    name: 'v3.11.1 🚀',
    draft: false,
    prerelease: false,
    created_at: '2022-06-27T18:45:03Z',
    published_at: '2022-06-27T19:50:56Z',
    assets: [],
    tarball_url: 'https://api.github.com/repos/aimhubio/aim/tarball/v3.11.1',
    zipball_url: 'https://api.github.com/repos/aimhubio/aim/zipball/v3.11.1',
    body: "## What's Changed\r\n* [fix] Resolve Notes tab loading issue in Run page by @arsengit in https://github.com/aimhubio/aim/pull/1912\r\n* [fix] Fix the loading logic of the `monaco editor` across the Aim Ui by @arsengit in https://github.com/aimhubio/aim/pull/1909\r\n* [feat] Allow mixing numeric types on a single Sequence by @alberttorosyan in https://github.com/aimhubio/aim/pull/1913\r\n* [fix] Fix Table export functionality in params and scatters explorers by @arsengit in https://github.com/aimhubio/aim/pull/1915\r\n* [feat] Optimize performance of the `encoder` by @KaroMourad in https://github.com/aimhubio/aim/pull/1895\r\n\r\n\r\n**Full Changelog**: https://github.com/aimhubio/aim/compare/v3.11.0...v3.11.1",
    reactions: {
      url: 'https://api.github.com/repos/aimhubio/aim/releases/70677729/reactions',
      total_count: 6,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 5,
      confused: 0,
      heart: 0,
      rocket: 1,
      eyes: 0,
    },
    mentions_count: 3,
  },
  {
    url: 'https://api.github.com/repos/aimhubio/aim/releases/69968618',
    assets_url:
      'https://api.github.com/repos/aimhubio/aim/releases/69968618/assets',
    upload_url:
      'https://uploads.github.com/repos/aimhubio/aim/releases/69968618/assets{?name,label}',
    html_url: 'https://github.com/aimhubio/aim/releases/tag/v3.11.0',
    id: 69968618,
    author: {
      login: 'gorarakelyan',
      id: 13848158,
      node_id: 'MDQ6VXNlcjEzODQ4MTU4',
      avatar_url: 'https://avatars.githubusercontent.com/u/13848158?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/gorarakelyan',
      html_url: 'https://github.com/gorarakelyan',
      followers_url: 'https://api.github.com/users/gorarakelyan/followers',
      following_url:
        'https://api.github.com/users/gorarakelyan/following{/other_user}',
      gists_url: 'https://api.github.com/users/gorarakelyan/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/gorarakelyan/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/gorarakelyan/subscriptions',
      organizations_url: 'https://api.github.com/users/gorarakelyan/orgs',
      repos_url: 'https://api.github.com/users/gorarakelyan/repos',
      events_url: 'https://api.github.com/users/gorarakelyan/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/gorarakelyan/received_events',
      type: 'User',
      site_admin: false,
    },
    node_id: 'RE_kwDOC02th84EK6Lq',
    tag_name: 'v3.11.0',
    target_commitish: 'main',
    name: 'v3.11.0 🚀',
    draft: false,
    prerelease: false,
    created_at: '2022-06-21T17:55:00Z',
    published_at: '2022-06-21T19:26:52Z',
    assets: [],
    tarball_url: 'https://api.github.com/repos/aimhubio/aim/tarball/v3.11.0',
    zipball_url: 'https://api.github.com/repos/aimhubio/aim/zipball/v3.11.0',
    body: "## What's Changed\r\n\r\n### Enhancements:\r\n\r\n- Add `--uds` option for `aim up` command (@mihran113)\r\n- Add progress reporting for search APIs and tqdm progress for SDK queries (@mihran113)\r\n- Add all the attributes of runs in the grouping popovers (@KaroMourad)\r\n- Display progress bar on Explorer pages when searching metadata (@KaroMourad)\r\n- Improve the processing speed for tb to aim converter (@osoblanco)\r\n- Adjust charts hover attributes position calculation and styles (@KaroMourad)\r\n- Improve formatting of numbers by setting maximum precision (@KaroMourad)\r\n- Add cloud storage backups to AWS S3 for aim repo runs (@karan2801)\r\n- Add LightGBM integration example (@gorarakelyan)\r\n- Add descriptive document titles for pages (@KaroMourad)\r\n- Implement unit-tests for aim SDK utils (@yeghiakoronian)\r\n- Display std.dev/err aggregated values in the table (@VkoHov)\r\n- Add `active` state indicator property for `aim.Run` (@mihran113)\r\n- Add `active` state indicators on the chart (@VkoHov)\r\n- Add ability to edit run name and description of run (@VkoHov)\r\n- Show the description in the sidebar of the run overview tab (@VkoHov)\r\n- Add all the attributes of run in the tooltip (@VkoHov)\r\n- Optimize the initial render time of Aim UI by using more lightweight font-family (@arsengit)\r\n- Use monaco editor as the syntax highlighter across the Aim UI (@arsengit)\r\n- Add loader to the top of the logs box in the run page (@VkoHov)\r\n- Add the date and the duration of run in the header of the single run page (@VkoHov)\r\n- Add the name, status and duration of run in the runs table of the tags page (@VkoHov)\r\n- Fit long name values in manage columns popover (@arsengit)\r\n- Add caching mechanism for sequence queries to optimize query performance (@mihran113)\r\n- Use step random hash as a key for metric sequences (@alberttorosyan)\r\n\r\n### Fixes:\r\n\r\n- Fix issue with tensorboard to aim conversion (@osoblanco)\r\n- Fix reset zoom history on alignment type change (@KaroMourad)\r\n- Fix issue with rendering incorrect data when x-axis aligned by `relative time/epoch` (@KaroMourad)\r\n- Fix LineCart axis ticks overlapping issue on log scale (@KaroMourad)\r\n- Change zooming default option to multiple (@VkoHov)\r\n- Change grouped rows' min and max values names to `Group Min` and `Group Max` (@VkoHov)\r\n- Preserve the search input value of the grouping dropdown (@VkoHov)\r\n- Change the titles and placeholders in popovers (@VkoHov)\r\n- Resolve typing latency issue in the query search input (@arsengit)\r\n- Reorder and add non-hideable table columns (@arsengit)\r\n- Change the font of the runs navigation popover (@VkoHov)\r\n- Keep color persistence state after page reload (@VkoHov)\r\n- Resolve content blinking issue after search in the run page (@arsengit)\r\n- Fix scroll to bottom on live-update in logs tab (@VkoHov)\r\n- Fix timezone issues for activity map (@mihran113)\r\n- Fix `aim up` command output when `--port 0` is passed (@mihran113)\r\n\r\n\r\n## New Contributors\r\n* @yeghiakoronian made their first contribution in https://github.com/aimhubio/aim/pull/1732\r\n* @hendriks73 made their first contribution in https://github.com/aimhubio/aim/pull/1769\r\n* @karan2801 made their first contribution in https://github.com/aimhubio/aim/pull/1787\r\n* @osoblanco made their first contribution in https://github.com/aimhubio/aim/pull/1847\r\n\r\n**Milestone**: https://github.com/aimhubio/aim/milestone/34\r\n**Full Changelog**: https://github.com/aimhubio/aim/compare/v3.10.3...v3.11.0",
    reactions: {
      url: 'https://api.github.com/repos/aimhubio/aim/releases/69968618/reactions',
      total_count: 2,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 1,
      confused: 0,
      heart: 0,
      rocket: 1,
      eyes: 0,
    },
    mentions_count: 10,
  },
  {
    url: 'https://api.github.com/repos/aimhubio/aim/releases/68268499',
    assets_url:
      'https://api.github.com/repos/aimhubio/aim/releases/68268499/assets',
    upload_url:
      'https://uploads.github.com/repos/aimhubio/aim/releases/68268499/assets{?name,label}',
    html_url: 'https://github.com/aimhubio/aim/releases/tag/v3.10.3',
    id: 68268499,
    author: {
      login: 'gorarakelyan',
      id: 13848158,
      node_id: 'MDQ6VXNlcjEzODQ4MTU4',
      avatar_url: 'https://avatars.githubusercontent.com/u/13848158?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/gorarakelyan',
      html_url: 'https://github.com/gorarakelyan',
      followers_url: 'https://api.github.com/users/gorarakelyan/followers',
      following_url:
        'https://api.github.com/users/gorarakelyan/following{/other_user}',
      gists_url: 'https://api.github.com/users/gorarakelyan/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/gorarakelyan/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/gorarakelyan/subscriptions',
      organizations_url: 'https://api.github.com/users/gorarakelyan/orgs',
      repos_url: 'https://api.github.com/users/gorarakelyan/repos',
      events_url: 'https://api.github.com/users/gorarakelyan/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/gorarakelyan/received_events',
      type: 'User',
      site_admin: false,
    },
    node_id: 'RE_kwDOC02th84EEbHT',
    tag_name: 'v3.10.3',
    target_commitish: 'main',
    name: 'v3.10.3 🚀',
    draft: false,
    prerelease: false,
    created_at: '2022-05-31T16:15:19Z',
    published_at: '2022-05-31T17:20:44Z',
    assets: [],
    tarball_url: 'https://api.github.com/repos/aimhubio/aim/tarball/v3.10.3',
    zipball_url: 'https://api.github.com/repos/aimhubio/aim/zipball/v3.10.3',
    body: '## May 26, 2022\r\n\r\n### Fixes:\r\n- Adjust the content overflowing of the Delete and the Archive modals (VkoHov)\r\n- Resolve issue with redirect in run page (arsengit)\r\n\r\n### Milestone:\r\nhttps://github.com/aimhubio/aim/milestone/35',
    reactions: {
      url: 'https://api.github.com/repos/aimhubio/aim/releases/68268499/reactions',
      total_count: 2,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 1,
      confused: 0,
      heart: 0,
      rocket: 1,
      eyes: 0,
    },
  },
  {
    url: 'https://api.github.com/repos/aimhubio/aim/releases/67927744',
    assets_url:
      'https://api.github.com/repos/aimhubio/aim/releases/67927744/assets',
    upload_url:
      'https://uploads.github.com/repos/aimhubio/aim/releases/67927744/assets{?name,label}',
    html_url: 'https://github.com/aimhubio/aim/releases/tag/v3.10.2',
    id: 67927744,
    author: {
      login: 'gorarakelyan',
      id: 13848158,
      node_id: 'MDQ6VXNlcjEzODQ4MTU4',
      avatar_url: 'https://avatars.githubusercontent.com/u/13848158?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/gorarakelyan',
      html_url: 'https://github.com/gorarakelyan',
      followers_url: 'https://api.github.com/users/gorarakelyan/followers',
      following_url:
        'https://api.github.com/users/gorarakelyan/following{/other_user}',
      gists_url: 'https://api.github.com/users/gorarakelyan/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/gorarakelyan/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/gorarakelyan/subscriptions',
      organizations_url: 'https://api.github.com/users/gorarakelyan/orgs',
      repos_url: 'https://api.github.com/users/gorarakelyan/repos',
      events_url: 'https://api.github.com/users/gorarakelyan/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/gorarakelyan/received_events',
      type: 'User',
      site_admin: false,
    },
    node_id: 'RE_kwDOC02th84EDH7A',
    tag_name: 'v3.10.2',
    target_commitish: 'main',
    name: 'v3.10.2 🚀',
    draft: false,
    prerelease: false,
    created_at: '2022-05-26T14:38:29Z',
    published_at: '2022-05-26T14:44:45Z',
    assets: [],
    tarball_url: 'https://api.github.com/repos/aimhubio/aim/tarball/v3.10.2',
    zipball_url: 'https://api.github.com/repos/aimhubio/aim/zipball/v3.10.2',
    body: '## May 26, 2022\r\n\r\n### Fixes:\r\n- Adjust SRP Logs row height calculation (VkoHov)\r\n- Fix issue with live update requests scheduler (rubenaprikyan)\r\n- Fix log capturing crash during run garbage collection (mihran113)\r\n- Fix Pytorch Lightning adapter `finalize` method (mihran113)\r\n- Fix params duplication in dropdowns (VkoHov)\r\n- Skip system params in Explorer pages (alberttorosyan)\r\n\r\n### Milestone:\r\nhttps://github.com/aimhubio/aim/milestone/35',
  },
  {
    url: 'https://api.github.com/repos/aimhubio/aim/releases/67210962',
    assets_url:
      'https://api.github.com/repos/aimhubio/aim/releases/67210962/assets',
    upload_url:
      'https://uploads.github.com/repos/aimhubio/aim/releases/67210962/assets{?name,label}',
    html_url: 'https://github.com/aimhubio/aim/releases/tag/v3.10.1',
    id: 67210962,
    author: {
      login: 'gorarakelyan',
      id: 13848158,
      node_id: 'MDQ6VXNlcjEzODQ4MTU4',
      avatar_url: 'https://avatars.githubusercontent.com/u/13848158?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/gorarakelyan',
      html_url: 'https://github.com/gorarakelyan',
      followers_url: 'https://api.github.com/users/gorarakelyan/followers',
      following_url:
        'https://api.github.com/users/gorarakelyan/following{/other_user}',
      gists_url: 'https://api.github.com/users/gorarakelyan/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/gorarakelyan/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/gorarakelyan/subscriptions',
      organizations_url: 'https://api.github.com/users/gorarakelyan/orgs',
      repos_url: 'https://api.github.com/users/gorarakelyan/repos',
      events_url: 'https://api.github.com/users/gorarakelyan/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/gorarakelyan/received_events',
      type: 'User',
      site_admin: false,
    },
    node_id: 'RE_kwDOC02th84EAY7S',
    tag_name: 'v3.10.1',
    target_commitish: 'main',
    name: 'v3.10.1 🚀',
    draft: false,
    prerelease: false,
    created_at: '2022-05-18T18:08:25Z',
    published_at: '2022-05-18T18:44:42Z',
    assets: [],
    tarball_url: 'https://api.github.com/repos/aimhubio/aim/tarball/v3.10.1',
    zipball_url: 'https://api.github.com/repos/aimhubio/aim/zipball/v3.10.1',
    body: '## May 18, 2022\r\n\r\n### Fixes:\r\n- Resolve issue with rendering run params in the overview tab of SRP (arsengit)\r\n- Fix issue with search query state update (arsengit)\r\n\r\n### Milestone:\r\nhttps://github.com/aimhubio/aim/milestone/35',
  },
  {
    url: 'https://api.github.com/repos/aimhubio/aim/releases/67108159',
    assets_url:
      'https://api.github.com/repos/aimhubio/aim/releases/67108159/assets',
    upload_url:
      'https://uploads.github.com/repos/aimhubio/aim/releases/67108159/assets{?name,label}',
    html_url: 'https://github.com/aimhubio/aim/releases/tag/v3.10.0',
    id: 67108159,
    author: {
      login: 'gorarakelyan',
      id: 13848158,
      node_id: 'MDQ6VXNlcjEzODQ4MTU4',
      avatar_url: 'https://avatars.githubusercontent.com/u/13848158?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/gorarakelyan',
      html_url: 'https://github.com/gorarakelyan',
      followers_url: 'https://api.github.com/users/gorarakelyan/followers',
      following_url:
        'https://api.github.com/users/gorarakelyan/following{/other_user}',
      gists_url: 'https://api.github.com/users/gorarakelyan/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/gorarakelyan/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/gorarakelyan/subscriptions',
      organizations_url: 'https://api.github.com/users/gorarakelyan/orgs',
      repos_url: 'https://api.github.com/users/gorarakelyan/repos',
      events_url: 'https://api.github.com/users/gorarakelyan/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/gorarakelyan/received_events',
      type: 'User',
      site_admin: false,
    },
    node_id: 'RE_kwDOC02th84D__0_',
    tag_name: 'v3.10.0',
    target_commitish: 'main',
    name: 'v3.10.0 🚀',
    draft: false,
    prerelease: false,
    created_at: '2022-05-17T18:37:28Z',
    published_at: '2022-05-17T18:41:38Z',
    assets: [],
    tarball_url: 'https://api.github.com/repos/aimhubio/aim/tarball/v3.10.0',
    zipball_url: 'https://api.github.com/repos/aimhubio/aim/zipball/v3.10.0',
    body: '## May 17, 2022\r\n\r\n### Enhancements:\r\n- Add ability to adjust the density of the visible content in tables (roubkar)\r\n- Set `metric.name` as default option for grouping (roubkar)\r\n- Show user-selected params before group config in chart popover (roubkar) \r\n- Optimize stream decoding performance on UI (mahnerak)\r\n- Add support for animated image formats to Aim Image object (devfox-se)\r\n- Add `AimLogger` for Catboost (devfox-se)\r\n- Add `AimCallback` for LightGBM (devfox-se)\r\n- Keep the extents of `HighPlot` axes brush in the state and the URL (VkoHov)\r\n- Integrate `aim` with `cimport`-able `aimrocks` (mahnerak)\r\n- Add `__slots__` to some classes to improve performance (mahnerak)\r\n- Define base abstractions for `Iterator` and `DB` by borrowing from `aimrocks` (mahnerak)\r\n- Use `KeysIterator` and `ValuesIterator` wrappers instead of reimplementing (mahnerak)\r\n- Rename `PrefixView.container` to `PrefixView.parent` (mahnerak)\r\n- Reimplement `absolute_path` (mahnerak)\r\n- Cython bindings for `PrefixView`, `TreeView`, `Container`, `ArrayView` (mahnerak)\r\n- Add ability to track and visualize stdout/stderr (mihran113, VkoHov)\r\n- Fix `AimLogger` deprecation issues related to release of PyTorch Lightning v1.5 (arnauddhaene)\r\n- Enable better autocomplete experience with monaco editor (arsengit)\r\n- Pre-loading and caching necessary resources, add pre-loader animation to Aim UI (arsengit) \r\n\r\n### Fixes:\r\n- Remove hard-coded installation of pre-requirements (mahnerak)\r\n- Remove duplicate code from `TreeView` and `Container` methods (mahnerak)\r\n- Fix issue with filtering metrics values in single run page (KaroMourad)\r\n\r\n### Milestone:\r\nhttps://github.com/aimhubio/aim/milestone/33',
    reactions: {
      url: 'https://api.github.com/repos/aimhubio/aim/releases/67108159/reactions',
      total_count: 2,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 2,
      eyes: 0,
    },
  },
  {
    url: 'https://api.github.com/repos/aimhubio/aim/releases/66631127',
    assets_url:
      'https://api.github.com/repos/aimhubio/aim/releases/66631127/assets',
    upload_url:
      'https://uploads.github.com/repos/aimhubio/aim/releases/66631127/assets{?name,label}',
    html_url: 'https://github.com/aimhubio/aim/releases/tag/v3.9.4',
    id: 66631127,
    author: {
      login: 'alberttorosyan',
      id: 32957250,
      node_id: 'MDQ6VXNlcjMyOTU3MjUw',
      avatar_url: 'https://avatars.githubusercontent.com/u/32957250?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/alberttorosyan',
      html_url: 'https://github.com/alberttorosyan',
      followers_url: 'https://api.github.com/users/alberttorosyan/followers',
      following_url:
        'https://api.github.com/users/alberttorosyan/following{/other_user}',
      gists_url: 'https://api.github.com/users/alberttorosyan/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/alberttorosyan/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/alberttorosyan/subscriptions',
      organizations_url: 'https://api.github.com/users/alberttorosyan/orgs',
      repos_url: 'https://api.github.com/users/alberttorosyan/repos',
      events_url:
        'https://api.github.com/users/alberttorosyan/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/alberttorosyan/received_events',
      type: 'User',
      site_admin: false,
    },
    node_id: 'RE_kwDOC02th84D-LXX',
    tag_name: 'v3.9.4',
    target_commitish: 'main',
    name: 'v3.9.4 🚀',
    draft: false,
    prerelease: false,
    created_at: '2022-05-11T21:51:34Z',
    published_at: '2022-05-11T22:05:51Z',
    assets: [],
    tarball_url: 'https://api.github.com/repos/aimhubio/aim/tarball/v3.9.4',
    zipball_url: 'https://api.github.com/repos/aimhubio/aim/zipball/v3.9.4',
    body: '## May 12, 2022\r\n\r\n### Fixes:\r\n- Fix run remote tracking queue cleanup (mihran113)\r\n- Fix HF callback before training access (mihran113)\r\n- Fix compatibility with Jinja 3.1 (devfox-se)\r\n\r\n### Milestone:\r\nhttps://github.com/aimhubio/aim/milestone/32',
  },
  {
    url: 'https://api.github.com/repos/aimhubio/aim/releases/66488209',
    assets_url:
      'https://api.github.com/repos/aimhubio/aim/releases/66488209/assets',
    upload_url:
      'https://uploads.github.com/repos/aimhubio/aim/releases/66488209/assets{?name,label}',
    html_url: 'https://github.com/aimhubio/aim/releases/tag/v3.9.3',
    id: 66488209,
    author: {
      login: 'gorarakelyan',
      id: 13848158,
      node_id: 'MDQ6VXNlcjEzODQ4MTU4',
      avatar_url: 'https://avatars.githubusercontent.com/u/13848158?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/gorarakelyan',
      html_url: 'https://github.com/gorarakelyan',
      followers_url: 'https://api.github.com/users/gorarakelyan/followers',
      following_url:
        'https://api.github.com/users/gorarakelyan/following{/other_user}',
      gists_url: 'https://api.github.com/users/gorarakelyan/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/gorarakelyan/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/gorarakelyan/subscriptions',
      organizations_url: 'https://api.github.com/users/gorarakelyan/orgs',
      repos_url: 'https://api.github.com/users/gorarakelyan/repos',
      events_url: 'https://api.github.com/users/gorarakelyan/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/gorarakelyan/received_events',
      type: 'User',
      site_admin: false,
    },
    node_id: 'RE_kwDOC02th84D9oeR',
    tag_name: 'v3.9.3',
    target_commitish: 'main',
    name: 'v3.9.3 🚀',
    draft: false,
    prerelease: false,
    created_at: '2022-05-10T15:18:50Z',
    published_at: '2022-05-10T15:25:39Z',
    assets: [],
    tarball_url: 'https://api.github.com/repos/aimhubio/aim/tarball/v3.9.3',
    zipball_url: 'https://api.github.com/repos/aimhubio/aim/zipball/v3.9.3',
    body: '## May 10, 2022\r\n\r\n### Fixes:\r\n- Fix affecting stroke types after changing color persistence (KaroMourad)',
  },
  {
    url: 'https://api.github.com/repos/aimhubio/aim/releases/65885859',
    assets_url:
      'https://api.github.com/repos/aimhubio/aim/releases/65885859/assets',
    upload_url:
      'https://uploads.github.com/repos/aimhubio/aim/releases/65885859/assets{?name,label}',
    html_url: 'https://github.com/aimhubio/aim/releases/tag/v3.9.2',
    id: 65885859,
    author: {
      login: 'alberttorosyan',
      id: 32957250,
      node_id: 'MDQ6VXNlcjMyOTU3MjUw',
      avatar_url: 'https://avatars.githubusercontent.com/u/32957250?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/alberttorosyan',
      html_url: 'https://github.com/alberttorosyan',
      followers_url: 'https://api.github.com/users/alberttorosyan/followers',
      following_url:
        'https://api.github.com/users/alberttorosyan/following{/other_user}',
      gists_url: 'https://api.github.com/users/alberttorosyan/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/alberttorosyan/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/alberttorosyan/subscriptions',
      organizations_url: 'https://api.github.com/users/alberttorosyan/orgs',
      repos_url: 'https://api.github.com/users/alberttorosyan/repos',
      events_url:
        'https://api.github.com/users/alberttorosyan/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/alberttorosyan/received_events',
      type: 'User',
      site_admin: false,
    },
    node_id: 'RE_kwDOC02th84D7Vaj',
    tag_name: 'v3.9.2',
    target_commitish: 'main',
    name: 'v3.9.2 🚀',
    draft: false,
    prerelease: false,
    created_at: '2022-05-03T07:18:41Z',
    published_at: '2022-05-03T07:19:53Z',
    assets: [],
    tarball_url: 'https://api.github.com/repos/aimhubio/aim/tarball/v3.9.2',
    zipball_url: 'https://api.github.com/repos/aimhubio/aim/zipball/v3.9.2',
    body: '## Apr 29, 2022\r\n\r\n### Fixes:\r\n- Move `aim_ui` package data to separate directory (devfox-se)',
  },
  {
    url: 'https://api.github.com/repos/aimhubio/aim/releases/65784208',
    assets_url:
      'https://api.github.com/repos/aimhubio/aim/releases/65784208/assets',
    upload_url:
      'https://uploads.github.com/repos/aimhubio/aim/releases/65784208/assets{?name,label}',
    html_url: 'https://github.com/aimhubio/aim/releases/tag/v3.9.1',
    id: 65784208,
    author: {
      login: 'alberttorosyan',
      id: 32957250,
      node_id: 'MDQ6VXNlcjMyOTU3MjUw',
      avatar_url: 'https://avatars.githubusercontent.com/u/32957250?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/alberttorosyan',
      html_url: 'https://github.com/alberttorosyan',
      followers_url: 'https://api.github.com/users/alberttorosyan/followers',
      following_url:
        'https://api.github.com/users/alberttorosyan/following{/other_user}',
      gists_url: 'https://api.github.com/users/alberttorosyan/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/alberttorosyan/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/alberttorosyan/subscriptions',
      organizations_url: 'https://api.github.com/users/alberttorosyan/orgs',
      repos_url: 'https://api.github.com/users/alberttorosyan/repos',
      events_url:
        'https://api.github.com/users/alberttorosyan/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/alberttorosyan/received_events',
      type: 'User',
      site_admin: false,
    },
    node_id: 'RE_kwDOC02th84D68mQ',
    tag_name: 'v3.9.1',
    target_commitish: 'main',
    name: 'v3.9.1 🚀',
    draft: false,
    prerelease: false,
    created_at: '2022-05-02T07:09:30Z',
    published_at: '2022-05-02T07:14:22Z',
    assets: [],
    tarball_url: 'https://api.github.com/repos/aimhubio/aim/tarball/v3.9.1',
    zipball_url: 'https://api.github.com/repos/aimhubio/aim/zipball/v3.9.1',
    body: '## Apr 29, 2022\r\n\r\n### Fixes:\r\n- Move `aim_ui` package data to separate directory (devfox-se)',
  },
  {
    url: 'https://api.github.com/repos/aimhubio/aim/releases/65673648',
    assets_url:
      'https://api.github.com/repos/aimhubio/aim/releases/65673648/assets',
    upload_url:
      'https://uploads.github.com/repos/aimhubio/aim/releases/65673648/assets{?name,label}',
    html_url: 'https://github.com/aimhubio/aim/releases/tag/v3.9.0',
    id: 65673648,
    author: {
      login: 'roubkar',
      id: 9951653,
      node_id: 'MDQ6VXNlcjk5NTE2NTM=',
      avatar_url: 'https://avatars.githubusercontent.com/u/9951653?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/roubkar',
      html_url: 'https://github.com/roubkar',
      followers_url: 'https://api.github.com/users/roubkar/followers',
      following_url:
        'https://api.github.com/users/roubkar/following{/other_user}',
      gists_url: 'https://api.github.com/users/roubkar/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/roubkar/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/roubkar/subscriptions',
      organizations_url: 'https://api.github.com/users/roubkar/orgs',
      repos_url: 'https://api.github.com/users/roubkar/repos',
      events_url: 'https://api.github.com/users/roubkar/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/roubkar/received_events',
      type: 'User',
      site_admin: false,
    },
    node_id: 'RE_kwDOC02th84D6hmw',
    tag_name: 'v3.9.0',
    target_commitish: 'main',
    name: 'v3.9.0 🚀',
    draft: false,
    prerelease: false,
    created_at: '2022-04-29T11:56:56Z',
    published_at: '2022-04-29T12:07:55Z',
    assets: [],
    tarball_url: 'https://api.github.com/repos/aimhubio/aim/tarball/v3.9.0',
    zipball_url: 'https://api.github.com/repos/aimhubio/aim/zipball/v3.9.0',
    body: "## Apr 29, 2022\r\n\r\n### Enhancements:\r\n\r\n- Add `Notes Tab` to single run page (arsengit)\r\n- Add the run name to the batch delete and the batch archive modals (VkoHov)\r\n- Increase the scalability of rendering lines in charts (KaroMourad)\r\n- Increase live update requests delay to prevent performance issues (rubenaprikyan)\r\n- Change font-family to monospace in the Table component (arsengit)\r\n- Add info massage for single value sliders (VkoHov)\r\n- Add `--log-level` argument for aim up/server commands (mihran113)\r\n- Add notes backend api interface (devfox-se)\r\n\r\n### Fixes:\r\n\r\n- Fix LineChart y-dimension margin calculation (KaroMourad)\r\n- Fix HighPlot lines partially rendering issue (KaroMourad)\r\n- Fix HighPlot axis ticks overlapping issue (KaroMourad)\r\n- Fix sorting Params/Scatters explorer axis ticks (KaroMourad)\r\n- Fix compatibility with pytorch-lightning v1.6.0 (mihran113)\r\n- Fix the image's original size cropping (VkoHov)\r\n- Fix `PATH` related issues for `alembic` and `uvicorn` (mihran113)\r\n- Fix queries for custom object APIs (mihran113)\r\n- Fix chart height updating when resize mode changed (VkoHov)\r\n- Fix HuggingFace callback context capturing (mihran113)\r\n- Fix Params/Scatters explorers' row hiding functionality (VkoHov)\r\n- Fix Profiler logs are saved outside repo directory (devfox-se) \r\n\r\n### Milestone:\r\nhttps://github.com/aimhubio/aim/milestone/31",
    reactions: {
      url: 'https://api.github.com/repos/aimhubio/aim/releases/65673648/reactions',
      total_count: 1,
      '+1': 1,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
  },
  {
    url: 'https://api.github.com/repos/aimhubio/aim/releases/63749926',
    assets_url:
      'https://api.github.com/repos/aimhubio/aim/releases/63749926/assets',
    upload_url:
      'https://uploads.github.com/repos/aimhubio/aim/releases/63749926/assets{?name,label}',
    html_url: 'https://github.com/aimhubio/aim/releases/tag/v3.8.1',
    id: 63749926,
    author: {
      login: 'roubkar',
      id: 9951653,
      node_id: 'MDQ6VXNlcjk5NTE2NTM=',
      avatar_url: 'https://avatars.githubusercontent.com/u/9951653?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/roubkar',
      html_url: 'https://github.com/roubkar',
      followers_url: 'https://api.github.com/users/roubkar/followers',
      following_url:
        'https://api.github.com/users/roubkar/following{/other_user}',
      gists_url: 'https://api.github.com/users/roubkar/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/roubkar/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/roubkar/subscriptions',
      organizations_url: 'https://api.github.com/users/roubkar/orgs',
      repos_url: 'https://api.github.com/users/roubkar/repos',
      events_url: 'https://api.github.com/users/roubkar/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/roubkar/received_events',
      type: 'User',
      site_admin: false,
    },
    node_id: 'RE_kwDOC02th84DzL8m',
    tag_name: 'v3.8.1',
    target_commitish: 'main',
    name: 'v3.8.1 🚀',
    draft: false,
    prerelease: false,
    created_at: '2022-04-06T13:35:19Z',
    published_at: '2022-04-06T13:40:00Z',
    assets: [],
    tarball_url: 'https://api.github.com/repos/aimhubio/aim/tarball/v3.8.1',
    zipball_url: 'https://api.github.com/repos/aimhubio/aim/zipball/v3.8.1',
    body: "## Apr 6, 2022\r\n\r\n### Fixes:\r\n\r\n- Encode run hash before including in CSS selectors (Hamik25)\r\n- Fix displaying incorrect metric values for large range scale in LineChart (KaroMourad)\r\n- Fix issue with rendering lines for large range scale in LineChart (KaroMourad)\r\n- Fix issue with URL state sync for bookmarks (roubkar)\r\n- Fix issue with displaying negative param values on Aim UI (roubkar)\r\n- Fix row hiding functionality (roubkar)\r\n- Tune RunOverviewTab container styles (arsengit)\r\n- Update documentations links on UI (rubenaprikyan)\r\n- Fix `RepoIndexManager` run's reference cleanup (mihran113)\r\n- Fix remote run finalization (mihran113)\r\n- Fix issue with fetch on load more (infinite scroll) functionality in Runs Explorer (rubenaprikyan)\r\n\r\n### Milestone:\r\nhttps://github.com/aimhubio/aim/milestone/30",
  },
  {
    url: 'https://api.github.com/repos/aimhubio/aim/releases/62815991',
    assets_url:
      'https://api.github.com/repos/aimhubio/aim/releases/62815991/assets',
    upload_url:
      'https://uploads.github.com/repos/aimhubio/aim/releases/62815991/assets{?name,label}',
    html_url: 'https://github.com/aimhubio/aim/releases/tag/v3.8.0',
    id: 62815991,
    author: {
      login: 'alberttorosyan',
      id: 32957250,
      node_id: 'MDQ6VXNlcjMyOTU3MjUw',
      avatar_url: 'https://avatars.githubusercontent.com/u/32957250?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/alberttorosyan',
      html_url: 'https://github.com/alberttorosyan',
      followers_url: 'https://api.github.com/users/alberttorosyan/followers',
      following_url:
        'https://api.github.com/users/alberttorosyan/following{/other_user}',
      gists_url: 'https://api.github.com/users/alberttorosyan/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/alberttorosyan/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/alberttorosyan/subscriptions',
      organizations_url: 'https://api.github.com/users/alberttorosyan/orgs',
      repos_url: 'https://api.github.com/users/alberttorosyan/repos',
      events_url:
        'https://api.github.com/users/alberttorosyan/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/alberttorosyan/received_events',
      type: 'User',
      site_admin: false,
    },
    node_id: 'RE_kwDOC02th84Dvn73',
    tag_name: 'v3.8.0',
    target_commitish: 'main',
    name: 'v3.8.0 🚀',
    draft: false,
    prerelease: false,
    created_at: '2022-03-25T20:26:30Z',
    published_at: '2022-03-25T20:35:31Z',
    assets: [],
    tarball_url: 'https://api.github.com/repos/aimhubio/aim/tarball/v3.8.0',
    zipball_url: 'https://api.github.com/repos/aimhubio/aim/zipball/v3.8.0',
    body: "## Mar 26 2022\r\n\r\n### Enhancements:\r\n\r\n- Hugging Face adapter refactoring (mihran113)\r\n- Add run description columns to all run specific tables (VkoHov, mihran113)\r\n- Change images rendering optimization default value to smoother (VkoHov)\r\n- Set default steps ordering to desc in single run tabs (VkoHov, devfox-se)\r\n- Add run name to grouping, ordering and run navigation popovers (VkoHov)\r\n- Add ability to apply color scale on columns with numeric values (VkoHov)\r\n- Refactored XGBoost AimCallback (devfox-se)\r\n- Reopenable callbacks for integrations (mihran113)\r\n- Add DVC integration (devfox-se)\r\n- Add API profiler and unified API error response (devfox-se)\r\n- Add API to retrieve N'th step of sequence (devfox-se)\r\n\r\n### Fixes:\r\n\r\n- Fix issue with calculation of active point on mouse hover in the LineChart (KaroMourad)\r\n- Fix issue with wrong URL caching for Explorer pages (roubkar)\r\n- Fix issue with focusing on the chart active point while moving the cursor (KaroMourad)\r\n- Fix the image full view toggle icon visibility if the image has a white background (VkoHov)\r\n- Fix scroll to the end of the audio tab (VkoHov)\r\n- Add scrollbar to image full view mode content (VkoHov)\r\n- Fix issues with run name/description not being set (mihran113)\r\n- Fix issue with run single page tabs result caching (mihran113)\r\n- Fix git system param tracking (devfox-se)\r\n- Fix runs manual closing (mihran113)\r\n- Fix Docker image creation step in packaging workflow (alberttorosyan)\r\n- Fix Jinja2 template rendering with starlette==0.14.2 (alberttorosyan)\r\n\r\n### Milestone:\r\nhttps://github.com/aimhubio/aim/milestone/29",
    reactions: {
      url: 'https://api.github.com/repos/aimhubio/aim/releases/62815991/reactions',
      total_count: 1,
      '+1': 1,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
  },
  {
    url: 'https://api.github.com/repos/aimhubio/aim/releases/62142362',
    assets_url:
      'https://api.github.com/repos/aimhubio/aim/releases/62142362/assets',
    upload_url:
      'https://uploads.github.com/repos/aimhubio/aim/releases/62142362/assets{?name,label}',
    html_url: 'https://github.com/aimhubio/aim/releases/tag/v3.7.5',
    id: 62142362,
    author: {
      login: 'roubkar',
      id: 9951653,
      node_id: 'MDQ6VXNlcjk5NTE2NTM=',
      avatar_url: 'https://avatars.githubusercontent.com/u/9951653?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/roubkar',
      html_url: 'https://github.com/roubkar',
      followers_url: 'https://api.github.com/users/roubkar/followers',
      following_url:
        'https://api.github.com/users/roubkar/following{/other_user}',
      gists_url: 'https://api.github.com/users/roubkar/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/roubkar/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/roubkar/subscriptions',
      organizations_url: 'https://api.github.com/users/roubkar/orgs',
      repos_url: 'https://api.github.com/users/roubkar/repos',
      events_url: 'https://api.github.com/users/roubkar/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/roubkar/received_events',
      type: 'User',
      site_admin: false,
    },
    node_id: 'RE_kwDOC02th84DtDea',
    tag_name: 'v3.7.5',
    target_commitish: 'main',
    name: 'v3.7.5 🚀',
    draft: false,
    prerelease: false,
    created_at: '2022-03-17T21:24:24Z',
    published_at: '2022-03-17T21:34:19Z',
    assets: [],
    tarball_url: 'https://api.github.com/repos/aimhubio/aim/tarball/v3.7.5',
    zipball_url: 'https://api.github.com/repos/aimhubio/aim/zipball/v3.7.5',
    body: '## Mar 18, 2022\r\n\r\n### Fixes:\r\n\r\n- Add request aborting functionality in single run page tabs (arsengit)\r\n- Render plotly figures properly in single run page (arsengit)\r\n\r\n### Milestone:\r\nhttps://github.com/aimhubio/aim/milestone/28',
    reactions: {
      url: 'https://api.github.com/repos/aimhubio/aim/releases/62142362/reactions',
      total_count: 1,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 1,
      rocket: 0,
      eyes: 0,
    },
  },
  {
    url: 'https://api.github.com/repos/aimhubio/aim/releases/61883273',
    assets_url:
      'https://api.github.com/repos/aimhubio/aim/releases/61883273/assets',
    upload_url:
      'https://uploads.github.com/repos/aimhubio/aim/releases/61883273/assets{?name,label}',
    html_url: 'https://github.com/aimhubio/aim/releases/tag/v3.7.4',
    id: 61883273,
    author: {
      login: 'alberttorosyan',
      id: 32957250,
      node_id: 'MDQ6VXNlcjMyOTU3MjUw',
      avatar_url: 'https://avatars.githubusercontent.com/u/32957250?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/alberttorosyan',
      html_url: 'https://github.com/alberttorosyan',
      followers_url: 'https://api.github.com/users/alberttorosyan/followers',
      following_url:
        'https://api.github.com/users/alberttorosyan/following{/other_user}',
      gists_url: 'https://api.github.com/users/alberttorosyan/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/alberttorosyan/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/alberttorosyan/subscriptions',
      organizations_url: 'https://api.github.com/users/alberttorosyan/orgs',
      repos_url: 'https://api.github.com/users/alberttorosyan/repos',
      events_url:
        'https://api.github.com/users/alberttorosyan/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/alberttorosyan/received_events',
      type: 'User',
      site_admin: false,
    },
    node_id: 'RE_kwDOC02th84DsEOJ',
    tag_name: 'v3.7.4',
    target_commitish: 'main',
    name: 'v3.7.4 🚀',
    draft: false,
    prerelease: false,
    created_at: '2022-03-15T12:21:51Z',
    published_at: '2022-03-15T13:15:00Z',
    assets: [],
    tarball_url: 'https://api.github.com/repos/aimhubio/aim/tarball/v3.7.4',
    zipball_url: 'https://api.github.com/repos/aimhubio/aim/zipball/v3.7.4',
    body: '## Mar 15, 2022\r\n\r\n### Fixes:\r\n\r\n- Fix density min and max validation calculation (VkoHov)\r\n\r\n### Milestone:\r\nhttps://github.com/aimhubio/aim/milestone/28',
  },
  {
    url: 'https://api.github.com/repos/aimhubio/aim/releases/61791100',
    assets_url:
      'https://api.github.com/repos/aimhubio/aim/releases/61791100/assets',
    upload_url:
      'https://uploads.github.com/repos/aimhubio/aim/releases/61791100/assets{?name,label}',
    html_url: 'https://github.com/aimhubio/aim/releases/tag/v3.7.3',
    id: 61791100,
    author: {
      login: 'alberttorosyan',
      id: 32957250,
      node_id: 'MDQ6VXNlcjMyOTU3MjUw',
      avatar_url: 'https://avatars.githubusercontent.com/u/32957250?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/alberttorosyan',
      html_url: 'https://github.com/alberttorosyan',
      followers_url: 'https://api.github.com/users/alberttorosyan/followers',
      following_url:
        'https://api.github.com/users/alberttorosyan/following{/other_user}',
      gists_url: 'https://api.github.com/users/alberttorosyan/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/alberttorosyan/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/alberttorosyan/subscriptions',
      organizations_url: 'https://api.github.com/users/alberttorosyan/orgs',
      repos_url: 'https://api.github.com/users/alberttorosyan/repos',
      events_url:
        'https://api.github.com/users/alberttorosyan/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/alberttorosyan/received_events',
      type: 'User',
      site_admin: false,
    },
    node_id: 'RE_kwDOC02th84Drtt8',
    tag_name: 'v3.7.3',
    target_commitish: 'main',
    name: 'v3.7.3 🚀',
    draft: false,
    prerelease: false,
    created_at: '2022-03-14T17:34:54Z',
    published_at: '2022-03-14T17:53:31Z',
    assets: [],
    tarball_url: 'https://api.github.com/repos/aimhubio/aim/tarball/v3.7.3',
    zipball_url: 'https://api.github.com/repos/aimhubio/aim/zipball/v3.7.3',
    body: '## Mar 14, 2022\r\n\r\n### Fixes:\r\n\r\n- Add missing names for dynamically imported files in single run page (arsengit)\r\n\r\n### Milestone:\r\nhttps://github.com/aimhubio/aim/milestone/28',
  },
  {
    url: 'https://api.github.com/repos/aimhubio/aim/releases/61528143',
    assets_url:
      'https://api.github.com/repos/aimhubio/aim/releases/61528143/assets',
    upload_url:
      'https://uploads.github.com/repos/aimhubio/aim/releases/61528143/assets{?name,label}',
    html_url: 'https://github.com/aimhubio/aim/releases/tag/v3.7.2',
    id: 61528143,
    author: {
      login: 'gorarakelyan',
      id: 13848158,
      node_id: 'MDQ6VXNlcjEzODQ4MTU4',
      avatar_url: 'https://avatars.githubusercontent.com/u/13848158?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/gorarakelyan',
      html_url: 'https://github.com/gorarakelyan',
      followers_url: 'https://api.github.com/users/gorarakelyan/followers',
      following_url:
        'https://api.github.com/users/gorarakelyan/following{/other_user}',
      gists_url: 'https://api.github.com/users/gorarakelyan/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/gorarakelyan/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/gorarakelyan/subscriptions',
      organizations_url: 'https://api.github.com/users/gorarakelyan/orgs',
      repos_url: 'https://api.github.com/users/gorarakelyan/repos',
      events_url: 'https://api.github.com/users/gorarakelyan/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/gorarakelyan/received_events',
      type: 'User',
      site_admin: false,
    },
    node_id: 'RE_kwDOC02th84DqthP',
    tag_name: 'v3.7.2',
    target_commitish: 'main',
    name: 'v3.7.2 🚀',
    draft: false,
    prerelease: false,
    created_at: '2022-03-10T18:33:35Z',
    published_at: '2022-03-10T18:37:28Z',
    assets: [],
    tarball_url: 'https://api.github.com/repos/aimhubio/aim/tarball/v3.7.2',
    zipball_url: 'https://api.github.com/repos/aimhubio/aim/zipball/v3.7.2',
    body: '## 3.7.2 Mar 10, 2022\r\n\r\n### Fixes:\r\n- Fix issue with rendering UI re keeping long URL (KaroMourad)\r\n\r\n### Enhancements:\r\n- Split code in the single run page to optimize chunk size (arsengit)\r\n\r\n### Milestone:\r\nhttps://github.com/aimhubio/aim/milestone/28',
  },
  {
    url: 'https://api.github.com/repos/aimhubio/aim/releases/61476074',
    assets_url:
      'https://api.github.com/repos/aimhubio/aim/releases/61476074/assets',
    upload_url:
      'https://uploads.github.com/repos/aimhubio/aim/releases/61476074/assets{?name,label}',
    html_url: 'https://github.com/aimhubio/aim/releases/tag/v3.7.1',
    id: 61476074,
    author: {
      login: 'alberttorosyan',
      id: 32957250,
      node_id: 'MDQ6VXNlcjMyOTU3MjUw',
      avatar_url: 'https://avatars.githubusercontent.com/u/32957250?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/alberttorosyan',
      html_url: 'https://github.com/alberttorosyan',
      followers_url: 'https://api.github.com/users/alberttorosyan/followers',
      following_url:
        'https://api.github.com/users/alberttorosyan/following{/other_user}',
      gists_url: 'https://api.github.com/users/alberttorosyan/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/alberttorosyan/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/alberttorosyan/subscriptions',
      organizations_url: 'https://api.github.com/users/alberttorosyan/orgs',
      repos_url: 'https://api.github.com/users/alberttorosyan/repos',
      events_url:
        'https://api.github.com/users/alberttorosyan/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/alberttorosyan/received_events',
      type: 'User',
      site_admin: false,
    },
    node_id: 'RE_kwDOC02th84Dqgzq',
    tag_name: 'v3.7.1',
    target_commitish: 'main',
    name: 'v3.7.1 🚀',
    draft: false,
    prerelease: false,
    created_at: '2022-03-10T09:24:56Z',
    published_at: '2022-03-10T09:42:28Z',
    assets: [],
    tarball_url: 'https://api.github.com/repos/aimhubio/aim/tarball/v3.7.1',
    zipball_url: 'https://api.github.com/repos/aimhubio/aim/zipball/v3.7.1',
    body: '## Mar 10, 2022\r\n\r\n### Fixes:\r\n\r\n- Fix metric queries with epoch=None (alberttorosyan)\r\n\r\n### Milestone:\r\nhttps://github.com/aimhubio/aim/milestone/28',
  },
  {
    url: 'https://api.github.com/repos/aimhubio/aim/releases/61377816',
    assets_url:
      'https://api.github.com/repos/aimhubio/aim/releases/61377816/assets',
    upload_url:
      'https://uploads.github.com/repos/aimhubio/aim/releases/61377816/assets{?name,label}',
    html_url: 'https://github.com/aimhubio/aim/releases/tag/v3.7.0',
    id: 61377816,
    author: {
      login: 'roubkar',
      id: 9951653,
      node_id: 'MDQ6VXNlcjk5NTE2NTM=',
      avatar_url: 'https://avatars.githubusercontent.com/u/9951653?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/roubkar',
      html_url: 'https://github.com/roubkar',
      followers_url: 'https://api.github.com/users/roubkar/followers',
      following_url:
        'https://api.github.com/users/roubkar/following{/other_user}',
      gists_url: 'https://api.github.com/users/roubkar/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/roubkar/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/roubkar/subscriptions',
      organizations_url: 'https://api.github.com/users/roubkar/orgs',
      repos_url: 'https://api.github.com/users/roubkar/repos',
      events_url: 'https://api.github.com/users/roubkar/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/roubkar/received_events',
      type: 'User',
      site_admin: false,
    },
    node_id: 'RE_kwDOC02th84DqI0Y',
    tag_name: 'v3.7.0',
    target_commitish: 'main',
    name: 'v3.7.0 🚀',
    draft: false,
    prerelease: false,
    created_at: '2022-03-09T14:07:38Z',
    published_at: '2022-03-09T14:28:48Z',
    assets: [],
    tarball_url: 'https://api.github.com/repos/aimhubio/aim/tarball/v3.7.0',
    zipball_url: 'https://api.github.com/repos/aimhubio/aim/zipball/v3.7.0',
    body: '## Mar 9, 2022\r\n\r\n### Enhancements:\r\n\r\n- Add Run overview tab in run single page (arsengit, VkoHov, KaroMourad, rubenaprikyan)\r\n- Custom max message size for Aim Remote tracking (alberttorosyan)\r\n- Docker images for aim up/server (alberttorosyan)\r\n- TF/Keras adapters refactoring (mihran113)\r\n- Remote tracking client-side retry logic (aramaim)\r\n- Add record_density to initial get-batch request for figures (VkoHov)\r\n\r\n### Fixes:\r\n\r\n- Fix rendering new lines in texts visualizer (arsengit)\r\n\r\n### Milestone:\r\nhttps://github.com/aimhubio/aim/milestone/27',
  },
  {
    url: 'https://api.github.com/repos/aimhubio/aim/releases/60996030',
    assets_url:
      'https://api.github.com/repos/aimhubio/aim/releases/60996030/assets',
    upload_url:
      'https://uploads.github.com/repos/aimhubio/aim/releases/60996030/assets{?name,label}',
    html_url: 'https://github.com/aimhubio/aim/releases/tag/v3.6.3',
    id: 60996030,
    author: {
      login: 'alberttorosyan',
      id: 32957250,
      node_id: 'MDQ6VXNlcjMyOTU3MjUw',
      avatar_url: 'https://avatars.githubusercontent.com/u/32957250?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/alberttorosyan',
      html_url: 'https://github.com/alberttorosyan',
      followers_url: 'https://api.github.com/users/alberttorosyan/followers',
      following_url:
        'https://api.github.com/users/alberttorosyan/following{/other_user}',
      gists_url: 'https://api.github.com/users/alberttorosyan/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/alberttorosyan/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/alberttorosyan/subscriptions',
      organizations_url: 'https://api.github.com/users/alberttorosyan/orgs',
      repos_url: 'https://api.github.com/users/alberttorosyan/repos',
      events_url:
        'https://api.github.com/users/alberttorosyan/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/alberttorosyan/received_events',
      type: 'User',
      site_admin: false,
    },
    node_id: 'RE_kwDOC02th84Dorm-',
    tag_name: 'v3.6.3',
    target_commitish: 'main',
    name: 'v3.6.3 🚀',
    draft: false,
    prerelease: false,
    created_at: '2022-03-04T14:25:58Z',
    published_at: '2022-03-04T14:30:09Z',
    assets: [],
    tarball_url: 'https://api.github.com/repos/aimhubio/aim/tarball/v3.6.3',
    zipball_url: 'https://api.github.com/repos/aimhubio/aim/zipball/v3.6.3',
    body: '## Mar 4, 2022\r\n\r\n### Fixes:\r\n\r\n- Fix UI rendering issue on colab (rubenaprikyan)\r\n\r\n### Milestone:\r\nhttps://github.com/aimhubio/aim/milestone/26',
  },
  {
    url: 'https://api.github.com/repos/aimhubio/aim/releases/60799410',
    assets_url:
      'https://api.github.com/repos/aimhubio/aim/releases/60799410/assets',
    upload_url:
      'https://uploads.github.com/repos/aimhubio/aim/releases/60799410/assets{?name,label}',
    html_url: 'https://github.com/aimhubio/aim/releases/tag/v3.6.2',
    id: 60799410,
    author: {
      login: 'alberttorosyan',
      id: 32957250,
      node_id: 'MDQ6VXNlcjMyOTU3MjUw',
      avatar_url: 'https://avatars.githubusercontent.com/u/32957250?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/alberttorosyan',
      html_url: 'https://github.com/alberttorosyan',
      followers_url: 'https://api.github.com/users/alberttorosyan/followers',
      following_url:
        'https://api.github.com/users/alberttorosyan/following{/other_user}',
      gists_url: 'https://api.github.com/users/alberttorosyan/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/alberttorosyan/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/alberttorosyan/subscriptions',
      organizations_url: 'https://api.github.com/users/alberttorosyan/orgs',
      repos_url: 'https://api.github.com/users/alberttorosyan/repos',
      events_url:
        'https://api.github.com/users/alberttorosyan/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/alberttorosyan/received_events',
      type: 'User',
      site_admin: false,
    },
    node_id: 'RE_kwDOC02th84Dn7my',
    tag_name: 'v3.6.2',
    target_commitish: 'main',
    name: 'v3.6.2 🚀',
    draft: false,
    prerelease: false,
    created_at: '2022-03-02T13:07:51Z',
    published_at: '2022-03-02T13:33:24Z',
    assets: [],
    tarball_url: 'https://api.github.com/repos/aimhubio/aim/tarball/v3.6.2',
    zipball_url: 'https://api.github.com/repos/aimhubio/aim/zipball/v3.6.2',
    body: '## Mar 2, 2022\r\n\r\n### Fixes:\r\n\r\n- Fix chart interactions issue in the Single Run Page Metrics tab (roubkar)\r\n- Fix `resolve_objects` in remote tracking client subtree (alberttorosyan)\r\n- Reject `0` as step/record count (alberttorosyan, VkoHov)\r\n- Fix error on mlflow conversion by experiment id (devfox-se)  \r\n\r\n\r\n### Milestone:\r\nhttps://github.com/aimhubio/aim/milestone/26',
  },
  {
    url: 'https://api.github.com/repos/aimhubio/aim/releases/60507710',
    assets_url:
      'https://api.github.com/repos/aimhubio/aim/releases/60507710/assets',
    upload_url:
      'https://uploads.github.com/repos/aimhubio/aim/releases/60507710/assets{?name,label}',
    html_url: 'https://github.com/aimhubio/aim/releases/tag/v3.6.1',
    id: 60507710,
    author: {
      login: 'alberttorosyan',
      id: 32957250,
      node_id: 'MDQ6VXNlcjMyOTU3MjUw',
      avatar_url: 'https://avatars.githubusercontent.com/u/32957250?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/alberttorosyan',
      html_url: 'https://github.com/alberttorosyan',
      followers_url: 'https://api.github.com/users/alberttorosyan/followers',
      following_url:
        'https://api.github.com/users/alberttorosyan/following{/other_user}',
      gists_url: 'https://api.github.com/users/alberttorosyan/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/alberttorosyan/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/alberttorosyan/subscriptions',
      organizations_url: 'https://api.github.com/users/alberttorosyan/orgs',
      repos_url: 'https://api.github.com/users/alberttorosyan/repos',
      events_url:
        'https://api.github.com/users/alberttorosyan/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/alberttorosyan/received_events',
      type: 'User',
      site_admin: false,
    },
    node_id: 'RE_kwDOC02th84Dm0Y-',
    tag_name: 'v3.6.1',
    target_commitish: 'main',
    name: 'v3.6.1 🚀',
    draft: false,
    prerelease: false,
    created_at: '2022-02-25T18:38:00Z',
    published_at: '2022-02-25T18:55:09Z',
    assets: [],
    tarball_url: 'https://api.github.com/repos/aimhubio/aim/tarball/v3.6.1',
    zipball_url: 'https://api.github.com/repos/aimhubio/aim/zipball/v3.6.1',
    body: "## Feb 25, 2022\r\n\r\n### Fixes:\r\n\r\n- Fix issue with aligning x-axis by custom metric (KaroMourad)\r\n- Add `__AIM_PROXY_URL__` env variable to see full proxy url when running `aim up` command(rubenaprikyan)\r\n- Add `--proxy-url` argument to notebook extension's `%aim up` to render UI correctly if there is a proxy server  (rubenaprikyan)\r\n- Add SageMaker integration, `jupyter-server-proxy` s bug-fix script (rubenaprikyan, mahnerak)\r\n- Fix animation support in Plotly visualization and figure loading performance (Hamik25, mihran113)\r\n- Display `None` values in group config column (VkoHov, Hamik25)\r\n- Fix rendering issue on `Select` form search suggestions list (arsengit)\r\n- Fix PL.AimLogger save_dir AttributeError (GeeeekExplorer)\r\n- Remove `__example_type__` substring from param name (VkoHov)\r\n\r\n\r\n### Milestone:\r\nhttps://github.com/aimhubio/aim/milestone/26",
  },
];
function ReleaseNotes(): React.FunctionComponentElement<React.ReactNode> {
  //   const { data, isLoading } = useReleaseNotes();
  return (
    <div className='ReleaseNotes'>
      <Text component='h4' tint={100} weight={700}>
        Aim v{AIM_VERSION}
      </Text>
      <Editor defaultValue={mock[0].body} />
    </div>
  );
}

export default React.memo(ReleaseNotes);
