# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: text.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='text.proto',
  package='artifacts.proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\ntext.proto\x12\x0f\x61rtifacts.proto\"\x1a\n\nTextRecord\x12\x0c\n\x04text\x18\x01 \x01(\tb\x06proto3'
)




_TEXTRECORD = _descriptor.Descriptor(
  name='TextRecord',
  full_name='artifacts.proto.TextRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='artifacts.proto.TextRecord.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=57,
)

DESCRIPTOR.message_types_by_name['TextRecord'] = _TEXTRECORD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TextRecord = _reflection.GeneratedProtocolMessageType('TextRecord', (_message.Message,), {
  'DESCRIPTOR' : _TEXTRECORD,
  '__module__' : 'text_pb2'
  # @@protoc_insertion_point(class_scope:artifacts.proto.TextRecord)
  })
_sym_db.RegisterMessage(TextRecord)


# @@protoc_insertion_point(module_scope)
