# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: remote_router.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='remote_router.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13remote_router.proto\"\x10\n\x0eVersionRequest\"h\n\x0fVersionResponse\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\'\n\x06status\x18\x02 \x01(\x0e\x32\x17.VersionResponse.Status\"\x1b\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01\"*\n\x14WorkerAddressRequest\x12\x12\n\nclient_uri\x18\x01 \x01(\t\"t\n\x15WorkerAddressResponse\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12-\n\x06status\x18\x02 \x01(\x0e\x32\x1d.WorkerAddressResponse.Status\"\x1b\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01\"-\n\x17\x43lientDisconnectRequest\x12\x12\n\nclient_uri\x18\x01 \x01(\t\"i\n\x18\x43lientDisconnectResponse\x12\x30\n\x06status\x18\x01 \x01(\x0e\x32 .ClientDisconnectResponse.Status\"\x1b\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x32\xdc\x01\n\x13RemoteRouterService\x12\x32\n\x0bget_version\x12\x0f.VersionRequest\x1a\x10.VersionResponse\"\x00\x12\x45\n\x12get_worker_address\x12\x15.WorkerAddressRequest\x1a\x16.WorkerAddressResponse\"\x00\x12J\n\x11\x63lient_disconnect\x12\x18.ClientDisconnectRequest\x1a\x19.ClientDisconnectResponse\"\x00\x62\x06proto3'
)



_VERSIONRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='VersionResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=118,
  serialized_end=145,
)
_sym_db.RegisterEnumDescriptor(_VERSIONRESPONSE_STATUS)

_WORKERADDRESSRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='WorkerAddressResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=118,
  serialized_end=145,
)
_sym_db.RegisterEnumDescriptor(_WORKERADDRESSRESPONSE_STATUS)

_CLIENTDISCONNECTRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='ClientDisconnectResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=118,
  serialized_end=145,
)
_sym_db.RegisterEnumDescriptor(_CLIENTDISCONNECTRESPONSE_STATUS)


_VERSIONREQUEST = _descriptor.Descriptor(
  name='VersionRequest',
  full_name='VersionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=39,
)


_VERSIONRESPONSE = _descriptor.Descriptor(
  name='VersionResponse',
  full_name='VersionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='VersionResponse.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='VersionResponse.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _VERSIONRESPONSE_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=145,
)


_WORKERADDRESSREQUEST = _descriptor.Descriptor(
  name='WorkerAddressRequest',
  full_name='WorkerAddressRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_uri', full_name='WorkerAddressRequest.client_uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=189,
)


_WORKERADDRESSRESPONSE = _descriptor.Descriptor(
  name='WorkerAddressResponse',
  full_name='WorkerAddressResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='WorkerAddressResponse.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='WorkerAddressResponse.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _WORKERADDRESSRESPONSE_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=307,
)


_CLIENTDISCONNECTREQUEST = _descriptor.Descriptor(
  name='ClientDisconnectRequest',
  full_name='ClientDisconnectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_uri', full_name='ClientDisconnectRequest.client_uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=354,
)


_CLIENTDISCONNECTRESPONSE = _descriptor.Descriptor(
  name='ClientDisconnectResponse',
  full_name='ClientDisconnectResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ClientDisconnectResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CLIENTDISCONNECTRESPONSE_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=356,
  serialized_end=461,
)

_VERSIONRESPONSE.fields_by_name['status'].enum_type = _VERSIONRESPONSE_STATUS
_VERSIONRESPONSE_STATUS.containing_type = _VERSIONRESPONSE
_WORKERADDRESSRESPONSE.fields_by_name['status'].enum_type = _WORKERADDRESSRESPONSE_STATUS
_WORKERADDRESSRESPONSE_STATUS.containing_type = _WORKERADDRESSRESPONSE
_CLIENTDISCONNECTRESPONSE.fields_by_name['status'].enum_type = _CLIENTDISCONNECTRESPONSE_STATUS
_CLIENTDISCONNECTRESPONSE_STATUS.containing_type = _CLIENTDISCONNECTRESPONSE
DESCRIPTOR.message_types_by_name['VersionRequest'] = _VERSIONREQUEST
DESCRIPTOR.message_types_by_name['VersionResponse'] = _VERSIONRESPONSE
DESCRIPTOR.message_types_by_name['WorkerAddressRequest'] = _WORKERADDRESSREQUEST
DESCRIPTOR.message_types_by_name['WorkerAddressResponse'] = _WORKERADDRESSRESPONSE
DESCRIPTOR.message_types_by_name['ClientDisconnectRequest'] = _CLIENTDISCONNECTREQUEST
DESCRIPTOR.message_types_by_name['ClientDisconnectResponse'] = _CLIENTDISCONNECTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VersionRequest = _reflection.GeneratedProtocolMessageType('VersionRequest', (_message.Message,), {
  'DESCRIPTOR' : _VERSIONREQUEST,
  '__module__' : 'remote_router_pb2'
  # @@protoc_insertion_point(class_scope:VersionRequest)
  })
_sym_db.RegisterMessage(VersionRequest)

VersionResponse = _reflection.GeneratedProtocolMessageType('VersionResponse', (_message.Message,), {
  'DESCRIPTOR' : _VERSIONRESPONSE,
  '__module__' : 'remote_router_pb2'
  # @@protoc_insertion_point(class_scope:VersionResponse)
  })
_sym_db.RegisterMessage(VersionResponse)

WorkerAddressRequest = _reflection.GeneratedProtocolMessageType('WorkerAddressRequest', (_message.Message,), {
  'DESCRIPTOR' : _WORKERADDRESSREQUEST,
  '__module__' : 'remote_router_pb2'
  # @@protoc_insertion_point(class_scope:WorkerAddressRequest)
  })
_sym_db.RegisterMessage(WorkerAddressRequest)

WorkerAddressResponse = _reflection.GeneratedProtocolMessageType('WorkerAddressResponse', (_message.Message,), {
  'DESCRIPTOR' : _WORKERADDRESSRESPONSE,
  '__module__' : 'remote_router_pb2'
  # @@protoc_insertion_point(class_scope:WorkerAddressResponse)
  })
_sym_db.RegisterMessage(WorkerAddressResponse)

ClientDisconnectRequest = _reflection.GeneratedProtocolMessageType('ClientDisconnectRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTDISCONNECTREQUEST,
  '__module__' : 'remote_router_pb2'
  # @@protoc_insertion_point(class_scope:ClientDisconnectRequest)
  })
_sym_db.RegisterMessage(ClientDisconnectRequest)

ClientDisconnectResponse = _reflection.GeneratedProtocolMessageType('ClientDisconnectResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTDISCONNECTRESPONSE,
  '__module__' : 'remote_router_pb2'
  # @@protoc_insertion_point(class_scope:ClientDisconnectResponse)
  })
_sym_db.RegisterMessage(ClientDisconnectResponse)



_REMOTEROUTERSERVICE = _descriptor.ServiceDescriptor(
  name='RemoteRouterService',
  full_name='RemoteRouterService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=464,
  serialized_end=684,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_version',
    full_name='RemoteRouterService.get_version',
    index=0,
    containing_service=None,
    input_type=_VERSIONREQUEST,
    output_type=_VERSIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_worker_address',
    full_name='RemoteRouterService.get_worker_address',
    index=1,
    containing_service=None,
    input_type=_WORKERADDRESSREQUEST,
    output_type=_WORKERADDRESSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='client_disconnect',
    full_name='RemoteRouterService.client_disconnect',
    index=2,
    containing_service=None,
    input_type=_CLIENTDISCONNECTREQUEST,
    output_type=_CLIENTDISCONNECTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_REMOTEROUTERSERVICE)

DESCRIPTOR.services_by_name['RemoteRouterService'] = _REMOTEROUTERSERVICE

# @@protoc_insertion_point(module_scope)
