"""empty message

Revision ID: fad1ea70fd4d
Revises: 5ae8371b7481
Create Date: 2021-08-09 02:40:48.930914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fad1ea70fd4d'
down_revision = '5ae8371b7481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commits')
    op.drop_table('tf_summary_logs')
    op.drop_table('tags')
    op.drop_table('commit_tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commit_tag',
    sa.Column('commit_id', sa.TEXT(), nullable=True),
    sa.Column('tag_id', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['commit_id'], ['commits.uuid'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.uuid'], )
    )
    op.create_table('tags',
    sa.Column('uuid', sa.TEXT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('color', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('is_archived', sa.BOOLEAN(), nullable=True),
    sa.Column('is_hidden', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('tf_summary_logs',
    sa.Column('uuid', sa.TEXT(), nullable=False),
    sa.Column('log_path', sa.TEXT(), nullable=True),
    sa.Column('params', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('is_archived', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('commits',
    sa.Column('uuid', sa.TEXT(), nullable=False),
    sa.Column('hash', sa.TEXT(), nullable=True),
    sa.Column('experiment_name', sa.TEXT(), nullable=True),
    sa.Column('session_started_at', sa.INTEGER(), nullable=True),
    sa.Column('session_closed_at', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('is_archived', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('experiment_name', 'hash')
    )
    # ### end Alembic commands ###
