// APP
export const APP = 'APP';

// WRAPPERS
export const BASE_WRAPPER = 'BASE_WRAPPER';
export const SITE_WRAPPER = 'SITE_WRAPPER';
export const HUB_WRAPPER = 'HUB_WRAPPER';
export const HUB_PROJECT_WRAPPER = 'HUB_PROJECT_WRAPPER';

// SITE SCREEN classes

// HUB SCREEN classes
export const HUB_MAIN_SCREEN = 'HUB_MAIN_SCREEN';
export const HUB_PROJECT_SCREEN = 'HUB_PROJECT_SCREEN';
export const HUB_PROJECT_EXPERIMENTS_DASHBOARD_SCREEN =
  'HUB_PROJECT_EXPERIMENTS_DASHBOARD_SCREEN';
export const HUB_PROJECT_EXPERIMENT_SCREEN = 'HUB_PROJECT_EXPERIMENT_SCREEN';
export const HUB_PROJECT_CREATE_EXECUTABLE = 'HUB_PROJECT_CREATE_EXECUTABLE';
export const HUB_PROJECT_EXECUTABLE_DETAIL = 'HUB_PROJECT_EXECUTABLE_DETAIL';
export const HUB_PROJECT_EXECUTABLE_PROCESS_DETAIL =
  'HUB_PROJECT_EXECUTABLE_PROCESS_DETAIL';
export const HUB_PROJECT_EXECUTABLES = 'HUB_PROJECT_EXECUTABLES';
export const HUB_PROJECT_TAGS = 'HUB_PROJECT_TAGS';
export const HUB_PROJECT_CREATE_TAG = 'HUB_PROJECT_CREATE_TAG';
export const HUB_PROJECT_EDIT_TAG = 'HUB_PROJECT_EDIT_TAG';
export const HUB_TF_SUMMARY_LIST_SCREEN = 'HUB_TF_SUMMARY_LIST_SCREEN';
export const HUB_BOOKMARKS_SCREEN = 'HUB_BOOKMARKS_SCREEN';

// COMPONENTS
export const HEADER = 'HEADER';
export const CONTROL_PANEL = 'CONTROL_PANEL';
export const PANEL_POPUPS = 'PANEL_POPUPS';
export const RUNNING_EXEC_LIST = 'RUNNING_EXEC_LIST';
export const EXPLORE_PARAMS_SELECT_INPUT = 'EXPLORE_PARAMS_SELECT_INPUT';
