export let SERVER_HOST, SERVER_API_HOST, WS_HOST;

if (window.app?.env === 'dev') {
  SERVER_HOST = 'http://127.0.0.1:43800';
  SERVER_API_HOST = `${SERVER_HOST}/api/v1`;
  WS_HOST = '';
} else {
  SERVER_HOST = `http://${window.location.hostname}:${window.location.port}`;
  SERVER_API_HOST = `${SERVER_HOST}/api/v1`;
  WS_HOST = '';
}

export const TIMEZONE_COOKIE_NAME = '__AIMDE__:TIMEZONE';
export const USER_ANALYTICS_COOKIE_NAME =
  '__AIMDE__:USER_ANALYTICS_COOKIE_NAME';
export const USER_LAST_SEARCH_QUERY = '__AIMDE__:USER_LAST_SEARCH_QUERY';
export const USER_LAST_EXPLORE_CONFIG = '__AIMDE__:USER_LAST_EXPLORE_CONFIG';
export const EXPLORE_PANEL_FLEX_STYLE = '__AIMDE__:EXPLORE_PANEL_FLEX_STYLE';
export const EXPLORE_PANEL_VIEW_MODE = '__AIMDE__:EXPLORE_PANEL_VIEW_MODE';
export const EXPLORE_METRIC_HIGHLIGHT_MODE =
  '__AIMDE__:EXPLORE_METRIC_HIGHLIGHT_MODE';
export const TABLE_COLUMNS = '__AIMDE__:TABLE_COLUMNS';
export const TABLE_COLUMNS_WIDTHS = '__AIMDE__:TABLE_COLUMNS_WIDTHS';
export const CONTEXT_TABLE_CONFIG = '__AIMDE__:CONTEXT_TABLE_CONFIG_{name}';
export const EXPLORE_PANEL_SORT_FIELDS = '__AIMDE__:EXPLORE_PANEL_SORT_FIELDS';
export const DASHBOARD_SORT_FIELDS = '__AIMDE__:DASHBOARD_SORT_FIELDS';
export const NUM_RUNS_KEY = '__AIMDE__:NUMBER_OF_RUNS';
export const NUM_EXPERIMENTS_KEY = '__AIMDE__:NUMBER_OF_EXPERIMENTS';
export const EXPLORE_PANEL_COLOR_PALETTE =
  '__AIMDE__:EXPLORE_PANEL_COLOR_PALETTE';
export const EXPLORE_PANEL_HIDDEN_METRICS =
  '__AIMDE__:EXPLORE_PANEL_HIDDEN_METRICS';
export const EXPLORE_PANEL_SINGLE_ZOOM_MODE =
  '__AIMDE__:EXPLORE_PANEL_SINGLE_ZOOM_MODE';
export const EXPLORE_PANEL_CHART_TOOLTIP_OPTIONS =
  '__AIMDE__:EXPLORE_PANEL_CHART_TOOLTIP_OPTIONS';

export const SEGMENT_DEMO_WRITE_KEY = 'Rj1I4AisLSvsvAnPW7OqkoYBUTXJRBHK';
export const SEGMENT_WRITE_KEY = 'LBnAonwto541z4Dn4ntGJScCsYNRdIC3';

export const AIM_QL_VERSION = 1;
